// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: orders/v1/order.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "../../shared/v1/struct";

export const protobufPackage = "orders.v1";

/** Payment status for an order */
export enum PaymentStatus {
  PAYMENT_UNKNOWN = 0,
  PAYMENT_AUTHORIZED = 1,
  PAYMENT_CAPTURED = 2,
  PAYMENT_FAILED = 3,
  UNRECOGNIZED = -1,
}

export function paymentStatusFromJSON(object: any): PaymentStatus {
  switch (object) {
    case 0:
    case "PAYMENT_UNKNOWN":
      return PaymentStatus.PAYMENT_UNKNOWN;
    case 1:
    case "PAYMENT_AUTHORIZED":
      return PaymentStatus.PAYMENT_AUTHORIZED;
    case 2:
    case "PAYMENT_CAPTURED":
      return PaymentStatus.PAYMENT_CAPTURED;
    case 3:
    case "PAYMENT_FAILED":
      return PaymentStatus.PAYMENT_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PaymentStatus.UNRECOGNIZED;
  }
}

export function paymentStatusToJSON(object: PaymentStatus): string {
  switch (object) {
    case PaymentStatus.PAYMENT_UNKNOWN:
      return "PAYMENT_UNKNOWN";
    case PaymentStatus.PAYMENT_AUTHORIZED:
      return "PAYMENT_AUTHORIZED";
    case PaymentStatus.PAYMENT_CAPTURED:
      return "PAYMENT_CAPTURED";
    case PaymentStatus.PAYMENT_FAILED:
      return "PAYMENT_FAILED";
    case PaymentStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Order status */
export enum OrderStatus {
  ORDER_STATUS_CREATED = 0,
  ORDER_STATUS_CONFIRMED = 1,
  ORDER_STATUS_SHIPPED = 2,
  ORDER_STATUS_DELIVERED = 3,
  ORDER_STATUS_CANCELLED = 4,
  ORDER_STATUS_REFUNDED = 5,
  ORDER_STATUS_REFUND_REQUESTED = 6,
  ORDER_STATUS_PAYMENT_SUCCEEDED = 7,
  ORDER_STATUS_PAYMENT_FAILED = 8,
  UNRECOGNIZED = -1,
}

export function orderStatusFromJSON(object: any): OrderStatus {
  switch (object) {
    case 0:
    case "ORDER_STATUS_CREATED":
      return OrderStatus.ORDER_STATUS_CREATED;
    case 1:
    case "ORDER_STATUS_CONFIRMED":
      return OrderStatus.ORDER_STATUS_CONFIRMED;
    case 2:
    case "ORDER_STATUS_SHIPPED":
      return OrderStatus.ORDER_STATUS_SHIPPED;
    case 3:
    case "ORDER_STATUS_DELIVERED":
      return OrderStatus.ORDER_STATUS_DELIVERED;
    case 4:
    case "ORDER_STATUS_CANCELLED":
      return OrderStatus.ORDER_STATUS_CANCELLED;
    case 5:
    case "ORDER_STATUS_REFUNDED":
      return OrderStatus.ORDER_STATUS_REFUNDED;
    case 6:
    case "ORDER_STATUS_REFUND_REQUESTED":
      return OrderStatus.ORDER_STATUS_REFUND_REQUESTED;
    case 7:
    case "ORDER_STATUS_PAYMENT_SUCCEEDED":
      return OrderStatus.ORDER_STATUS_PAYMENT_SUCCEEDED;
    case 8:
    case "ORDER_STATUS_PAYMENT_FAILED":
      return OrderStatus.ORDER_STATUS_PAYMENT_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderStatus.UNRECOGNIZED;
  }
}

export function orderStatusToJSON(object: OrderStatus): string {
  switch (object) {
    case OrderStatus.ORDER_STATUS_CREATED:
      return "ORDER_STATUS_CREATED";
    case OrderStatus.ORDER_STATUS_CONFIRMED:
      return "ORDER_STATUS_CONFIRMED";
    case OrderStatus.ORDER_STATUS_SHIPPED:
      return "ORDER_STATUS_SHIPPED";
    case OrderStatus.ORDER_STATUS_DELIVERED:
      return "ORDER_STATUS_DELIVERED";
    case OrderStatus.ORDER_STATUS_CANCELLED:
      return "ORDER_STATUS_CANCELLED";
    case OrderStatus.ORDER_STATUS_REFUNDED:
      return "ORDER_STATUS_REFUNDED";
    case OrderStatus.ORDER_STATUS_REFUND_REQUESTED:
      return "ORDER_STATUS_REFUND_REQUESTED";
    case OrderStatus.ORDER_STATUS_PAYMENT_SUCCEEDED:
      return "ORDER_STATUS_PAYMENT_SUCCEEDED";
    case OrderStatus.ORDER_STATUS_PAYMENT_FAILED:
      return "ORDER_STATUS_PAYMENT_FAILED";
    case OrderStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Order {
  id: string;
  userId: string;
  currencyCode: string;
  /** All price fields in cents */
  subtotalCents: string;
  shippingCents: string;
  taxCents: string;
  discountCents: string;
  totalCents: string;
  /** Payment information */
  paymentProvider: string;
  paymentTransactionId: string;
  paymentStatus: string;
  paymentProviderResponse?: Struct | undefined;
  paymentFeeCents: string;
  /** Inventory status */
  inventoryReservationStatus: string;
  /** Product information */
  productSource: string;
  /** Address snapshots */
  shippingAddress?: Struct | undefined;
  billingAddress?:
    | Struct
    | undefined;
  /** Metadata */
  metadata?: Struct | undefined;
  status: string;
  /** Timestamps */
  createdAt: string;
  updatedAt?: string | undefined;
  deletedAt?: string | undefined;
}

function createBaseOrder(): Order {
  return {
    id: "",
    userId: "",
    currencyCode: "",
    subtotalCents: "0",
    shippingCents: "0",
    taxCents: "0",
    discountCents: "0",
    totalCents: "0",
    paymentProvider: "",
    paymentTransactionId: "",
    paymentStatus: "",
    paymentProviderResponse: undefined,
    paymentFeeCents: "0",
    inventoryReservationStatus: "",
    productSource: "",
    shippingAddress: undefined,
    billingAddress: undefined,
    metadata: undefined,
    status: "",
    createdAt: "0",
    updatedAt: undefined,
    deletedAt: undefined,
  };
}

export const Order: MessageFns<Order> = {
  encode(message: Order, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.currencyCode !== "") {
      writer.uint32(26).string(message.currencyCode);
    }
    if (message.subtotalCents !== "0") {
      writer.uint32(32).uint64(message.subtotalCents);
    }
    if (message.shippingCents !== "0") {
      writer.uint32(40).uint64(message.shippingCents);
    }
    if (message.taxCents !== "0") {
      writer.uint32(48).uint64(message.taxCents);
    }
    if (message.discountCents !== "0") {
      writer.uint32(56).uint64(message.discountCents);
    }
    if (message.totalCents !== "0") {
      writer.uint32(64).uint64(message.totalCents);
    }
    if (message.paymentProvider !== "") {
      writer.uint32(74).string(message.paymentProvider);
    }
    if (message.paymentTransactionId !== "") {
      writer.uint32(82).string(message.paymentTransactionId);
    }
    if (message.paymentStatus !== "") {
      writer.uint32(90).string(message.paymentStatus);
    }
    if (message.paymentProviderResponse !== undefined) {
      Struct.encode(message.paymentProviderResponse, writer.uint32(98).fork()).join();
    }
    if (message.paymentFeeCents !== "0") {
      writer.uint32(104).uint64(message.paymentFeeCents);
    }
    if (message.inventoryReservationStatus !== "") {
      writer.uint32(114).string(message.inventoryReservationStatus);
    }
    if (message.productSource !== "") {
      writer.uint32(122).string(message.productSource);
    }
    if (message.shippingAddress !== undefined) {
      Struct.encode(message.shippingAddress, writer.uint32(130).fork()).join();
    }
    if (message.billingAddress !== undefined) {
      Struct.encode(message.billingAddress, writer.uint32(138).fork()).join();
    }
    if (message.metadata !== undefined) {
      Struct.encode(message.metadata, writer.uint32(146).fork()).join();
    }
    if (message.status !== "") {
      writer.uint32(154).string(message.status);
    }
    if (message.createdAt !== "0") {
      writer.uint32(160).uint64(message.createdAt);
    }
    if (message.updatedAt !== undefined) {
      writer.uint32(168).uint64(message.updatedAt);
    }
    if (message.deletedAt !== undefined) {
      writer.uint32(176).uint64(message.deletedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Order {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrder();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currencyCode = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.subtotalCents = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.shippingCents = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.taxCents = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.discountCents = reader.uint64().toString();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.totalCents = reader.uint64().toString();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.paymentProvider = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.paymentTransactionId = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.paymentStatus = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.paymentProviderResponse = Struct.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.paymentFeeCents = reader.uint64().toString();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.inventoryReservationStatus = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.productSource = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.shippingAddress = Struct.decode(reader, reader.uint32());
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.billingAddress = Struct.decode(reader, reader.uint32());
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.metadata = Struct.decode(reader, reader.uint32());
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.createdAt = reader.uint64().toString();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.updatedAt = reader.uint64().toString();
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.deletedAt = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Order {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      currencyCode: isSet(object.currencyCode) ? globalThis.String(object.currencyCode) : "",
      subtotalCents: isSet(object.subtotalCents) ? globalThis.String(object.subtotalCents) : "0",
      shippingCents: isSet(object.shippingCents) ? globalThis.String(object.shippingCents) : "0",
      taxCents: isSet(object.taxCents) ? globalThis.String(object.taxCents) : "0",
      discountCents: isSet(object.discountCents) ? globalThis.String(object.discountCents) : "0",
      totalCents: isSet(object.totalCents) ? globalThis.String(object.totalCents) : "0",
      paymentProvider: isSet(object.paymentProvider) ? globalThis.String(object.paymentProvider) : "",
      paymentTransactionId: isSet(object.paymentTransactionId) ? globalThis.String(object.paymentTransactionId) : "",
      paymentStatus: isSet(object.paymentStatus) ? globalThis.String(object.paymentStatus) : "",
      paymentProviderResponse: isSet(object.paymentProviderResponse)
        ? Struct.fromJSON(object.paymentProviderResponse)
        : undefined,
      paymentFeeCents: isSet(object.paymentFeeCents) ? globalThis.String(object.paymentFeeCents) : "0",
      inventoryReservationStatus: isSet(object.inventoryReservationStatus)
        ? globalThis.String(object.inventoryReservationStatus)
        : "",
      productSource: isSet(object.productSource) ? globalThis.String(object.productSource) : "",
      shippingAddress: isSet(object.shippingAddress) ? Struct.fromJSON(object.shippingAddress) : undefined,
      billingAddress: isSet(object.billingAddress) ? Struct.fromJSON(object.billingAddress) : undefined,
      metadata: isSet(object.metadata) ? Struct.fromJSON(object.metadata) : undefined,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "0",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : undefined,
      deletedAt: isSet(object.deletedAt) ? globalThis.String(object.deletedAt) : undefined,
    };
  },

  toJSON(message: Order): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.currencyCode !== "") {
      obj.currencyCode = message.currencyCode;
    }
    if (message.subtotalCents !== "0") {
      obj.subtotalCents = message.subtotalCents;
    }
    if (message.shippingCents !== "0") {
      obj.shippingCents = message.shippingCents;
    }
    if (message.taxCents !== "0") {
      obj.taxCents = message.taxCents;
    }
    if (message.discountCents !== "0") {
      obj.discountCents = message.discountCents;
    }
    if (message.totalCents !== "0") {
      obj.totalCents = message.totalCents;
    }
    if (message.paymentProvider !== "") {
      obj.paymentProvider = message.paymentProvider;
    }
    if (message.paymentTransactionId !== "") {
      obj.paymentTransactionId = message.paymentTransactionId;
    }
    if (message.paymentStatus !== "") {
      obj.paymentStatus = message.paymentStatus;
    }
    if (message.paymentProviderResponse !== undefined) {
      obj.paymentProviderResponse = Struct.toJSON(message.paymentProviderResponse);
    }
    if (message.paymentFeeCents !== "0") {
      obj.paymentFeeCents = message.paymentFeeCents;
    }
    if (message.inventoryReservationStatus !== "") {
      obj.inventoryReservationStatus = message.inventoryReservationStatus;
    }
    if (message.productSource !== "") {
      obj.productSource = message.productSource;
    }
    if (message.shippingAddress !== undefined) {
      obj.shippingAddress = Struct.toJSON(message.shippingAddress);
    }
    if (message.billingAddress !== undefined) {
      obj.billingAddress = Struct.toJSON(message.billingAddress);
    }
    if (message.metadata !== undefined) {
      obj.metadata = Struct.toJSON(message.metadata);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt;
    }
    if (message.deletedAt !== undefined) {
      obj.deletedAt = message.deletedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Order>, I>>(base?: I): Order {
    return Order.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Order>, I>>(object: I): Order {
    const message = createBaseOrder();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.currencyCode = object.currencyCode ?? "";
    message.subtotalCents = object.subtotalCents ?? "0";
    message.shippingCents = object.shippingCents ?? "0";
    message.taxCents = object.taxCents ?? "0";
    message.discountCents = object.discountCents ?? "0";
    message.totalCents = object.totalCents ?? "0";
    message.paymentProvider = object.paymentProvider ?? "";
    message.paymentTransactionId = object.paymentTransactionId ?? "";
    message.paymentStatus = object.paymentStatus ?? "";
    message.paymentProviderResponse =
      (object.paymentProviderResponse !== undefined && object.paymentProviderResponse !== null)
        ? Struct.fromPartial(object.paymentProviderResponse)
        : undefined;
    message.paymentFeeCents = object.paymentFeeCents ?? "0";
    message.inventoryReservationStatus = object.inventoryReservationStatus ?? "";
    message.productSource = object.productSource ?? "";
    message.shippingAddress = (object.shippingAddress !== undefined && object.shippingAddress !== null)
      ? Struct.fromPartial(object.shippingAddress)
      : undefined;
    message.billingAddress = (object.billingAddress !== undefined && object.billingAddress !== null)
      ? Struct.fromPartial(object.billingAddress)
      : undefined;
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Struct.fromPartial(object.metadata)
      : undefined;
    message.status = object.status ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? undefined;
    message.deletedAt = object.deletedAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
