// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: orders/v1/order_get.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  InventoryReservationStatus,
  inventoryReservationStatusFromJSON,
  inventoryReservationStatusToJSON,
} from "../../inventory/v1/reservation_get";
import { AppError } from "../../shared/v1/error";
import { Any } from "../../shared/v1/types";
import { OrderLineItem } from "./order_line_items";

export const protobufPackage = "orders.v1";

export interface OrderItem {
  id: string;
  /** monetary amounts are stored in minor units (cents) to avoid float errors */
  subtotalCents: string;
  shippingCents: string;
  taxCents: string;
  discountCents: string;
  totalCents: string;
  currencyCode: string;
  /** line items snapshot */
  lineItems: OrderLineItem[];
  /** shipping & billing addresses (snapshot) */
  shippingAddress?: Any | undefined;
  billingAddress?:
    | Any
    | undefined;
  /** Payment snapshot (synchronous capture info) */
  payment?:
    | PaymentSnapshot
    | undefined;
  /**
   * Inventory reservation status - since inventory service is separate,
   * we include reservation status in order so UI shows what's reserved.
   */
  inventoryReservationStatus: InventoryReservationStatus;
  /** order lifecycle */
  status: string;
  createdAt: string;
  updatedAt?:
    | string
    | undefined;
  /** product/service traceability */
  productSource: string;
  /** product_version that was used for snapshot */
  productVersion: string;
  /** free-form metadata */
  metadata: { [key: string]: string };
}

export interface OrderItem_MetadataEntry {
  key: string;
  value: string;
}

/**
 * //////////////////////////////////////////////////////////////////////////////
 * Payment snapshot (synchronous capture)
 * //////////////////////////////////////////////////////////////////////////////
 */
export interface PaymentSnapshot {
  /** provider e.g., "stripe" */
  provider: string;
  /** provider transaction id (gateway charge id) */
  transactionId: string;
  /** capture status: AUTHORIZED/CAPTURED/FAILED */
  status: string;
  /** card token or payment method id (tokenized) */
  paymentMethod: string;
  /** provider raw response for auditing (tokenized, avoid PII) */
  providerResponse?:
    | Any
    | undefined;
  /** payment fees (in cents) charged by gateway, optional */
  feeCents?: string | undefined;
}

export interface OrderGetRequest {
  orderId: string;
}

export interface OrderGetResponse {
  data?: OrderItem | undefined;
  error?: AppError | undefined;
}

function createBaseOrderItem(): OrderItem {
  return {
    id: "",
    subtotalCents: "0",
    shippingCents: "0",
    taxCents: "0",
    discountCents: "0",
    totalCents: "0",
    currencyCode: "",
    lineItems: [],
    shippingAddress: undefined,
    billingAddress: undefined,
    payment: undefined,
    inventoryReservationStatus: 0,
    status: "",
    createdAt: "0",
    updatedAt: undefined,
    productSource: "",
    productVersion: "",
    metadata: {},
  };
}

export const OrderItem: MessageFns<OrderItem> = {
  encode(message: OrderItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.subtotalCents !== "0") {
      writer.uint32(24).uint64(message.subtotalCents);
    }
    if (message.shippingCents !== "0") {
      writer.uint32(32).uint64(message.shippingCents);
    }
    if (message.taxCents !== "0") {
      writer.uint32(40).uint64(message.taxCents);
    }
    if (message.discountCents !== "0") {
      writer.uint32(48).uint64(message.discountCents);
    }
    if (message.totalCents !== "0") {
      writer.uint32(56).uint64(message.totalCents);
    }
    if (message.currencyCode !== "") {
      writer.uint32(66).string(message.currencyCode);
    }
    for (const v of message.lineItems) {
      OrderLineItem.encode(v!, writer.uint32(74).fork()).join();
    }
    if (message.shippingAddress !== undefined) {
      Any.encode(message.shippingAddress, writer.uint32(82).fork()).join();
    }
    if (message.billingAddress !== undefined) {
      Any.encode(message.billingAddress, writer.uint32(90).fork()).join();
    }
    if (message.payment !== undefined) {
      PaymentSnapshot.encode(message.payment, writer.uint32(98).fork()).join();
    }
    if (message.inventoryReservationStatus !== 0) {
      writer.uint32(104).int32(message.inventoryReservationStatus);
    }
    if (message.status !== "") {
      writer.uint32(114).string(message.status);
    }
    if (message.createdAt !== "0") {
      writer.uint32(120).uint64(message.createdAt);
    }
    if (message.updatedAt !== undefined) {
      writer.uint32(128).uint64(message.updatedAt);
    }
    if (message.productSource !== "") {
      writer.uint32(138).string(message.productSource);
    }
    if (message.productVersion !== "") {
      writer.uint32(146).string(message.productVersion);
    }
    Object.entries(message.metadata).forEach(([key, value]) => {
      OrderItem_MetadataEntry.encode({ key: key as any, value }, writer.uint32(154).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.subtotalCents = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.shippingCents = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.taxCents = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.discountCents = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalCents = reader.uint64().toString();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.currencyCode = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.lineItems.push(OrderLineItem.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.shippingAddress = Any.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.billingAddress = Any.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.payment = PaymentSnapshot.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.inventoryReservationStatus = reader.int32() as any;
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.createdAt = reader.uint64().toString();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.updatedAt = reader.uint64().toString();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.productSource = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.productVersion = reader.string();
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          const entry19 = OrderItem_MetadataEntry.decode(reader, reader.uint32());
          if (entry19.value !== undefined) {
            message.metadata[entry19.key] = entry19.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      subtotalCents: isSet(object.subtotalCents) ? globalThis.String(object.subtotalCents) : "0",
      shippingCents: isSet(object.shippingCents) ? globalThis.String(object.shippingCents) : "0",
      taxCents: isSet(object.taxCents) ? globalThis.String(object.taxCents) : "0",
      discountCents: isSet(object.discountCents) ? globalThis.String(object.discountCents) : "0",
      totalCents: isSet(object.totalCents) ? globalThis.String(object.totalCents) : "0",
      currencyCode: isSet(object.currencyCode) ? globalThis.String(object.currencyCode) : "",
      lineItems: globalThis.Array.isArray(object?.lineItems)
        ? object.lineItems.map((e: any) => OrderLineItem.fromJSON(e))
        : [],
      shippingAddress: isSet(object.shippingAddress) ? Any.fromJSON(object.shippingAddress) : undefined,
      billingAddress: isSet(object.billingAddress) ? Any.fromJSON(object.billingAddress) : undefined,
      payment: isSet(object.payment) ? PaymentSnapshot.fromJSON(object.payment) : undefined,
      inventoryReservationStatus: isSet(object.inventoryReservationStatus)
        ? inventoryReservationStatusFromJSON(object.inventoryReservationStatus)
        : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "0",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : undefined,
      productSource: isSet(object.productSource) ? globalThis.String(object.productSource) : "",
      productVersion: isSet(object.productVersion) ? globalThis.String(object.productVersion) : "",
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: OrderItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.subtotalCents !== "0") {
      obj.subtotalCents = message.subtotalCents;
    }
    if (message.shippingCents !== "0") {
      obj.shippingCents = message.shippingCents;
    }
    if (message.taxCents !== "0") {
      obj.taxCents = message.taxCents;
    }
    if (message.discountCents !== "0") {
      obj.discountCents = message.discountCents;
    }
    if (message.totalCents !== "0") {
      obj.totalCents = message.totalCents;
    }
    if (message.currencyCode !== "") {
      obj.currencyCode = message.currencyCode;
    }
    if (message.lineItems?.length) {
      obj.lineItems = message.lineItems.map((e) => OrderLineItem.toJSON(e));
    }
    if (message.shippingAddress !== undefined) {
      obj.shippingAddress = Any.toJSON(message.shippingAddress);
    }
    if (message.billingAddress !== undefined) {
      obj.billingAddress = Any.toJSON(message.billingAddress);
    }
    if (message.payment !== undefined) {
      obj.payment = PaymentSnapshot.toJSON(message.payment);
    }
    if (message.inventoryReservationStatus !== 0) {
      obj.inventoryReservationStatus = inventoryReservationStatusToJSON(message.inventoryReservationStatus);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt;
    }
    if (message.productSource !== "") {
      obj.productSource = message.productSource;
    }
    if (message.productVersion !== "") {
      obj.productVersion = message.productVersion;
    }
    if (message.metadata) {
      const entries = Object.entries(message.metadata);
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderItem>, I>>(base?: I): OrderItem {
    return OrderItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderItem>, I>>(object: I): OrderItem {
    const message = createBaseOrderItem();
    message.id = object.id ?? "";
    message.subtotalCents = object.subtotalCents ?? "0";
    message.shippingCents = object.shippingCents ?? "0";
    message.taxCents = object.taxCents ?? "0";
    message.discountCents = object.discountCents ?? "0";
    message.totalCents = object.totalCents ?? "0";
    message.currencyCode = object.currencyCode ?? "";
    message.lineItems = object.lineItems?.map((e) => OrderLineItem.fromPartial(e)) || [];
    message.shippingAddress = (object.shippingAddress !== undefined && object.shippingAddress !== null)
      ? Any.fromPartial(object.shippingAddress)
      : undefined;
    message.billingAddress = (object.billingAddress !== undefined && object.billingAddress !== null)
      ? Any.fromPartial(object.billingAddress)
      : undefined;
    message.payment = (object.payment !== undefined && object.payment !== null)
      ? PaymentSnapshot.fromPartial(object.payment)
      : undefined;
    message.inventoryReservationStatus = object.inventoryReservationStatus ?? 0;
    message.status = object.status ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? undefined;
    message.productSource = object.productSource ?? "";
    message.productVersion = object.productVersion ?? "";
    message.metadata = Object.entries(object.metadata ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseOrderItem_MetadataEntry(): OrderItem_MetadataEntry {
  return { key: "", value: "" };
}

export const OrderItem_MetadataEntry: MessageFns<OrderItem_MetadataEntry> = {
  encode(message: OrderItem_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderItem_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderItem_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderItem_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: OrderItem_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderItem_MetadataEntry>, I>>(base?: I): OrderItem_MetadataEntry {
    return OrderItem_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderItem_MetadataEntry>, I>>(object: I): OrderItem_MetadataEntry {
    const message = createBaseOrderItem_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBasePaymentSnapshot(): PaymentSnapshot {
  return {
    provider: "",
    transactionId: "",
    status: "",
    paymentMethod: "",
    providerResponse: undefined,
    feeCents: undefined,
  };
}

export const PaymentSnapshot: MessageFns<PaymentSnapshot> = {
  encode(message: PaymentSnapshot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.provider !== "") {
      writer.uint32(10).string(message.provider);
    }
    if (message.transactionId !== "") {
      writer.uint32(18).string(message.transactionId);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    if (message.paymentMethod !== "") {
      writer.uint32(34).string(message.paymentMethod);
    }
    if (message.providerResponse !== undefined) {
      Any.encode(message.providerResponse, writer.uint32(42).fork()).join();
    }
    if (message.feeCents !== undefined) {
      writer.uint32(48).uint64(message.feeCents);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PaymentSnapshot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaymentSnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.transactionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.paymentMethod = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.providerResponse = Any.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.feeCents = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaymentSnapshot {
    return {
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
      transactionId: isSet(object.transactionId) ? globalThis.String(object.transactionId) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      paymentMethod: isSet(object.paymentMethod) ? globalThis.String(object.paymentMethod) : "",
      providerResponse: isSet(object.providerResponse) ? Any.fromJSON(object.providerResponse) : undefined,
      feeCents: isSet(object.feeCents) ? globalThis.String(object.feeCents) : undefined,
    };
  },

  toJSON(message: PaymentSnapshot): unknown {
    const obj: any = {};
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.transactionId !== "") {
      obj.transactionId = message.transactionId;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.paymentMethod !== "") {
      obj.paymentMethod = message.paymentMethod;
    }
    if (message.providerResponse !== undefined) {
      obj.providerResponse = Any.toJSON(message.providerResponse);
    }
    if (message.feeCents !== undefined) {
      obj.feeCents = message.feeCents;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaymentSnapshot>, I>>(base?: I): PaymentSnapshot {
    return PaymentSnapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaymentSnapshot>, I>>(object: I): PaymentSnapshot {
    const message = createBasePaymentSnapshot();
    message.provider = object.provider ?? "";
    message.transactionId = object.transactionId ?? "";
    message.status = object.status ?? "";
    message.paymentMethod = object.paymentMethod ?? "";
    message.providerResponse = (object.providerResponse !== undefined && object.providerResponse !== null)
      ? Any.fromPartial(object.providerResponse)
      : undefined;
    message.feeCents = object.feeCents ?? undefined;
    return message;
  },
};

function createBaseOrderGetRequest(): OrderGetRequest {
  return { orderId: "" };
}

export const OrderGetRequest: MessageFns<OrderGetRequest> = {
  encode(message: OrderGetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderGetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderGetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderGetRequest {
    return { orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "" };
  },

  toJSON(message: OrderGetRequest): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderGetRequest>, I>>(base?: I): OrderGetRequest {
    return OrderGetRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderGetRequest>, I>>(object: I): OrderGetRequest {
    const message = createBaseOrderGetRequest();
    message.orderId = object.orderId ?? "";
    return message;
  },
};

function createBaseOrderGetResponse(): OrderGetResponse {
  return { data: undefined, error: undefined };
}

export const OrderGetResponse: MessageFns<OrderGetResponse> = {
  encode(message: OrderGetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      OrderItem.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderGetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderGetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = OrderItem.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderGetResponse {
    return {
      data: isSet(object.data) ? OrderItem.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: OrderGetResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = OrderItem.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderGetResponse>, I>>(base?: I): OrderGetResponse {
    return OrderGetResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderGetResponse>, I>>(object: I): OrderGetResponse {
    const message = createBaseOrderGetResponse();
    message.data = (object.data !== undefined && object.data !== null) ? OrderItem.fromPartial(object.data) : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
