// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: orders/v1/orders.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { OrderCancelRequest, OrderCancelResponse } from "./order_cancel";
import { OrderCreateRequest, OrderCreateResponse } from "./order_create";
import { OrderGetRequest, OrderGetResponse } from "./order_get";
import { OrderRefundRequest, OrderRefundResponse } from "./order_refund";
import { OrdersListRequest, OrdersListResponse } from "./orders_list";
import {
  PaymentAddMethodRequest,
  PaymentAddMethodResponse,
  PaymentMakeDefaultRequest,
  PaymentMakeDefaultResponse,
  PaymentRemoveMethodRequest,
  PaymentRemoveMethodResponse,
  PaymentsListRequest,
  PaymentsListResponse,
} from "./payment_method";

export const protobufPackage = "orders.v1";

export type OrdersServiceService = typeof OrdersServiceService;
export const OrdersServiceService = {
  /** Create order: synchronous payment capture. Returns order snapshot if success. */
  orderCreate: {
    path: "/orders.v1.OrdersService/OrderCreate",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: OrderCreateRequest): Buffer => Buffer.from(OrderCreateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): OrderCreateRequest => OrderCreateRequest.decode(value),
    responseSerialize: (value: OrderCreateResponse): Buffer => Buffer.from(OrderCreateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): OrderCreateResponse => OrderCreateResponse.decode(value),
  },
  /** Get order by id */
  orderGet: {
    path: "/orders.v1.OrdersService/OrderGet",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: OrderGetRequest): Buffer => Buffer.from(OrderGetRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): OrderGetRequest => OrderGetRequest.decode(value),
    responseSerialize: (value: OrderGetResponse): Buffer => Buffer.from(OrderGetResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): OrderGetResponse => OrderGetResponse.decode(value),
  },
  /** List orders for user (with simple pagination) */
  ordersList: {
    path: "/orders.v1.OrdersService/OrdersList",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: OrdersListRequest): Buffer => Buffer.from(OrdersListRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): OrdersListRequest => OrdersListRequest.decode(value),
    responseSerialize: (value: OrdersListResponse): Buffer => Buffer.from(OrdersListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): OrdersListResponse => OrdersListResponse.decode(value),
  },
  /** Cancel order (subject to business rules). Refunds handled separately. */
  orderCancel: {
    path: "/orders.v1.OrdersService/OrderCancel",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: OrderCancelRequest): Buffer => Buffer.from(OrderCancelRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): OrderCancelRequest => OrderCancelRequest.decode(value),
    responseSerialize: (value: OrderCancelResponse): Buffer => Buffer.from(OrderCancelResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): OrderCancelResponse => OrderCancelResponse.decode(value),
  },
  /** Refund an order or order line(s) */
  orderRefund: {
    path: "/orders.v1.OrdersService/OrderRefund",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: OrderRefundRequest): Buffer => Buffer.from(OrderRefundRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): OrderRefundRequest => OrderRefundRequest.decode(value),
    responseSerialize: (value: OrderRefundResponse): Buffer => Buffer.from(OrderRefundResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): OrderRefundResponse => OrderRefundResponse.decode(value),
  },
  /** Payment methods */
  paymentAddMethod: {
    path: "/orders.v1.OrdersService/PaymentAddMethod",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PaymentAddMethodRequest): Buffer =>
      Buffer.from(PaymentAddMethodRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PaymentAddMethodRequest => PaymentAddMethodRequest.decode(value),
    responseSerialize: (value: PaymentAddMethodResponse): Buffer =>
      Buffer.from(PaymentAddMethodResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PaymentAddMethodResponse => PaymentAddMethodResponse.decode(value),
  },
  paymentRemoveMethod: {
    path: "/orders.v1.OrdersService/PaymentRemoveMethod",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PaymentRemoveMethodRequest): Buffer =>
      Buffer.from(PaymentRemoveMethodRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PaymentRemoveMethodRequest => PaymentRemoveMethodRequest.decode(value),
    responseSerialize: (value: PaymentRemoveMethodResponse): Buffer =>
      Buffer.from(PaymentRemoveMethodResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PaymentRemoveMethodResponse => PaymentRemoveMethodResponse.decode(value),
  },
  paymentMakeDefault: {
    path: "/orders.v1.OrdersService/PaymentMakeDefault",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PaymentMakeDefaultRequest): Buffer =>
      Buffer.from(PaymentMakeDefaultRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PaymentMakeDefaultRequest => PaymentMakeDefaultRequest.decode(value),
    responseSerialize: (value: PaymentMakeDefaultResponse): Buffer =>
      Buffer.from(PaymentMakeDefaultResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PaymentMakeDefaultResponse => PaymentMakeDefaultResponse.decode(value),
  },
  paymentsList: {
    path: "/orders.v1.OrdersService/PaymentsList",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PaymentsListRequest): Buffer => Buffer.from(PaymentsListRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PaymentsListRequest => PaymentsListRequest.decode(value),
    responseSerialize: (value: PaymentsListResponse): Buffer =>
      Buffer.from(PaymentsListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PaymentsListResponse => PaymentsListResponse.decode(value),
  },
} as const;

export interface OrdersServiceServer extends UntypedServiceImplementation {
  /** Create order: synchronous payment capture. Returns order snapshot if success. */
  orderCreate: handleUnaryCall<OrderCreateRequest, OrderCreateResponse>;
  /** Get order by id */
  orderGet: handleUnaryCall<OrderGetRequest, OrderGetResponse>;
  /** List orders for user (with simple pagination) */
  ordersList: handleUnaryCall<OrdersListRequest, OrdersListResponse>;
  /** Cancel order (subject to business rules). Refunds handled separately. */
  orderCancel: handleUnaryCall<OrderCancelRequest, OrderCancelResponse>;
  /** Refund an order or order line(s) */
  orderRefund: handleUnaryCall<OrderRefundRequest, OrderRefundResponse>;
  /** Payment methods */
  paymentAddMethod: handleUnaryCall<PaymentAddMethodRequest, PaymentAddMethodResponse>;
  paymentRemoveMethod: handleUnaryCall<PaymentRemoveMethodRequest, PaymentRemoveMethodResponse>;
  paymentMakeDefault: handleUnaryCall<PaymentMakeDefaultRequest, PaymentMakeDefaultResponse>;
  paymentsList: handleUnaryCall<PaymentsListRequest, PaymentsListResponse>;
}

export interface OrdersServiceClient extends Client {
  /** Create order: synchronous payment capture. Returns order snapshot if success. */
  orderCreate(
    request: OrderCreateRequest,
    callback: (error: ServiceError | null, response: OrderCreateResponse) => void,
  ): ClientUnaryCall;
  orderCreate(
    request: OrderCreateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OrderCreateResponse) => void,
  ): ClientUnaryCall;
  orderCreate(
    request: OrderCreateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OrderCreateResponse) => void,
  ): ClientUnaryCall;
  /** Get order by id */
  orderGet(
    request: OrderGetRequest,
    callback: (error: ServiceError | null, response: OrderGetResponse) => void,
  ): ClientUnaryCall;
  orderGet(
    request: OrderGetRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OrderGetResponse) => void,
  ): ClientUnaryCall;
  orderGet(
    request: OrderGetRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OrderGetResponse) => void,
  ): ClientUnaryCall;
  /** List orders for user (with simple pagination) */
  ordersList(
    request: OrdersListRequest,
    callback: (error: ServiceError | null, response: OrdersListResponse) => void,
  ): ClientUnaryCall;
  ordersList(
    request: OrdersListRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OrdersListResponse) => void,
  ): ClientUnaryCall;
  ordersList(
    request: OrdersListRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OrdersListResponse) => void,
  ): ClientUnaryCall;
  /** Cancel order (subject to business rules). Refunds handled separately. */
  orderCancel(
    request: OrderCancelRequest,
    callback: (error: ServiceError | null, response: OrderCancelResponse) => void,
  ): ClientUnaryCall;
  orderCancel(
    request: OrderCancelRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OrderCancelResponse) => void,
  ): ClientUnaryCall;
  orderCancel(
    request: OrderCancelRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OrderCancelResponse) => void,
  ): ClientUnaryCall;
  /** Refund an order or order line(s) */
  orderRefund(
    request: OrderRefundRequest,
    callback: (error: ServiceError | null, response: OrderRefundResponse) => void,
  ): ClientUnaryCall;
  orderRefund(
    request: OrderRefundRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OrderRefundResponse) => void,
  ): ClientUnaryCall;
  orderRefund(
    request: OrderRefundRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OrderRefundResponse) => void,
  ): ClientUnaryCall;
  /** Payment methods */
  paymentAddMethod(
    request: PaymentAddMethodRequest,
    callback: (error: ServiceError | null, response: PaymentAddMethodResponse) => void,
  ): ClientUnaryCall;
  paymentAddMethod(
    request: PaymentAddMethodRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PaymentAddMethodResponse) => void,
  ): ClientUnaryCall;
  paymentAddMethod(
    request: PaymentAddMethodRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PaymentAddMethodResponse) => void,
  ): ClientUnaryCall;
  paymentRemoveMethod(
    request: PaymentRemoveMethodRequest,
    callback: (error: ServiceError | null, response: PaymentRemoveMethodResponse) => void,
  ): ClientUnaryCall;
  paymentRemoveMethod(
    request: PaymentRemoveMethodRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PaymentRemoveMethodResponse) => void,
  ): ClientUnaryCall;
  paymentRemoveMethod(
    request: PaymentRemoveMethodRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PaymentRemoveMethodResponse) => void,
  ): ClientUnaryCall;
  paymentMakeDefault(
    request: PaymentMakeDefaultRequest,
    callback: (error: ServiceError | null, response: PaymentMakeDefaultResponse) => void,
  ): ClientUnaryCall;
  paymentMakeDefault(
    request: PaymentMakeDefaultRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PaymentMakeDefaultResponse) => void,
  ): ClientUnaryCall;
  paymentMakeDefault(
    request: PaymentMakeDefaultRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PaymentMakeDefaultResponse) => void,
  ): ClientUnaryCall;
  paymentsList(
    request: PaymentsListRequest,
    callback: (error: ServiceError | null, response: PaymentsListResponse) => void,
  ): ClientUnaryCall;
  paymentsList(
    request: PaymentsListRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PaymentsListResponse) => void,
  ): ClientUnaryCall;
  paymentsList(
    request: PaymentsListRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PaymentsListResponse) => void,
  ): ClientUnaryCall;
}

export const OrdersServiceClient = makeGenericClientConstructor(
  OrdersServiceService,
  "orders.v1.OrdersService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): OrdersServiceClient;
  service: typeof OrdersServiceService;
  serviceName: string;
};
