// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: products/v1/product_snapshot.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error";
import { ProductOffer } from "./product";

export const protobufPackage = "products.v1";

/** minimal product data used mostly for creating orders */
export interface ProductSnapshot {
  id: string;
  title: string;
  version: number;
  schemaVersion: number;
  offer?: ProductOffer | undefined;
}

export interface ProductSnapshotRequest {
  productId: string;
}

export interface ProductSnapshotResponse {
  data?: ProductSnapshot | undefined;
  error?: AppError | undefined;
}

function createBaseProductSnapshot(): ProductSnapshot {
  return { id: "", title: "", version: 0, schemaVersion: 0, offer: undefined };
}

export const ProductSnapshot: MessageFns<ProductSnapshot> = {
  encode(message: ProductSnapshot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.version !== 0) {
      writer.uint32(24).uint32(message.version);
    }
    if (message.schemaVersion !== 0) {
      writer.uint32(32).uint32(message.schemaVersion);
    }
    if (message.offer !== undefined) {
      ProductOffer.encode(message.offer, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductSnapshot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductSnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.schemaVersion = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.offer = ProductOffer.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductSnapshot {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      schemaVersion: isSet(object.schemaVersion) ? globalThis.Number(object.schemaVersion) : 0,
      offer: isSet(object.offer) ? ProductOffer.fromJSON(object.offer) : undefined,
    };
  },

  toJSON(message: ProductSnapshot): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.schemaVersion !== 0) {
      obj.schemaVersion = Math.round(message.schemaVersion);
    }
    if (message.offer !== undefined) {
      obj.offer = ProductOffer.toJSON(message.offer);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductSnapshot>, I>>(base?: I): ProductSnapshot {
    return ProductSnapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductSnapshot>, I>>(object: I): ProductSnapshot {
    const message = createBaseProductSnapshot();
    message.id = object.id ?? "";
    message.title = object.title ?? "";
    message.version = object.version ?? 0;
    message.schemaVersion = object.schemaVersion ?? 0;
    message.offer = (object.offer !== undefined && object.offer !== null)
      ? ProductOffer.fromPartial(object.offer)
      : undefined;
    return message;
  },
};

function createBaseProductSnapshotRequest(): ProductSnapshotRequest {
  return { productId: "" };
}

export const ProductSnapshotRequest: MessageFns<ProductSnapshotRequest> = {
  encode(message: ProductSnapshotRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductSnapshotRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductSnapshotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductSnapshotRequest {
    return { productId: isSet(object.productId) ? globalThis.String(object.productId) : "" };
  },

  toJSON(message: ProductSnapshotRequest): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductSnapshotRequest>, I>>(base?: I): ProductSnapshotRequest {
    return ProductSnapshotRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductSnapshotRequest>, I>>(object: I): ProductSnapshotRequest {
    const message = createBaseProductSnapshotRequest();
    message.productId = object.productId ?? "";
    return message;
  },
};

function createBaseProductSnapshotResponse(): ProductSnapshotResponse {
  return { data: undefined, error: undefined };
}

export const ProductSnapshotResponse: MessageFns<ProductSnapshotResponse> = {
  encode(message: ProductSnapshotResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      ProductSnapshot.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductSnapshotResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductSnapshotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = ProductSnapshot.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductSnapshotResponse {
    return {
      data: isSet(object.data) ? ProductSnapshot.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: ProductSnapshotResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = ProductSnapshot.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductSnapshotResponse>, I>>(base?: I): ProductSnapshotResponse {
    return ProductSnapshotResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductSnapshotResponse>, I>>(object: I): ProductSnapshotResponse {
    const message = createBaseProductSnapshotResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? ProductSnapshot.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
