// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: products/v1/products_to_like.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error";
import { PaginationRequest, PaginationResponse } from "../../shared/v1/pagination";

export const protobufPackage = "products.v1";

export enum ProductShippingMethod {
  PRODUCT_SHIPPING_METHOD_UNSPECIFIED = 0,
  PRODUCT_SHIPPING_METHOD_STANDARD = 1,
  PRODUCT_SHIPPING_METHOD_EXPRESS = 2,
  UNRECOGNIZED = -1,
}

export function productShippingMethodFromJSON(object: any): ProductShippingMethod {
  switch (object) {
    case 0:
    case "PRODUCT_SHIPPING_METHOD_UNSPECIFIED":
      return ProductShippingMethod.PRODUCT_SHIPPING_METHOD_UNSPECIFIED;
    case 1:
    case "PRODUCT_SHIPPING_METHOD_STANDARD":
      return ProductShippingMethod.PRODUCT_SHIPPING_METHOD_STANDARD;
    case 2:
    case "PRODUCT_SHIPPING_METHOD_EXPRESS":
      return ProductShippingMethod.PRODUCT_SHIPPING_METHOD_EXPRESS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProductShippingMethod.UNRECOGNIZED;
  }
}

export function productShippingMethodToJSON(object: ProductShippingMethod): string {
  switch (object) {
    case ProductShippingMethod.PRODUCT_SHIPPING_METHOD_UNSPECIFIED:
      return "PRODUCT_SHIPPING_METHOD_UNSPECIFIED";
    case ProductShippingMethod.PRODUCT_SHIPPING_METHOD_STANDARD:
      return "PRODUCT_SHIPPING_METHOD_STANDARD";
    case ProductShippingMethod.PRODUCT_SHIPPING_METHOD_EXPRESS:
      return "PRODUCT_SHIPPING_METHOD_EXPRESS";
    case ProductShippingMethod.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ProductItemMetadataType {
  PRODUCT_ITEM_METADATA_TYPE_UNSPECIFIED = 0,
  PRODUCT_ITEM_METADATA_TYPE_COUPON = 1,
  PRODUCT_ITEM_METADATA_TYPE_NEW_SHOPPER = 2,
  PRODUCT_ITEM_METADATA_TYPE_BUNDLE = 3,
  UNRECOGNIZED = -1,
}

export function productItemMetadataTypeFromJSON(object: any): ProductItemMetadataType {
  switch (object) {
    case 0:
    case "PRODUCT_ITEM_METADATA_TYPE_UNSPECIFIED":
      return ProductItemMetadataType.PRODUCT_ITEM_METADATA_TYPE_UNSPECIFIED;
    case 1:
    case "PRODUCT_ITEM_METADATA_TYPE_COUPON":
      return ProductItemMetadataType.PRODUCT_ITEM_METADATA_TYPE_COUPON;
    case 2:
    case "PRODUCT_ITEM_METADATA_TYPE_NEW_SHOPPER":
      return ProductItemMetadataType.PRODUCT_ITEM_METADATA_TYPE_NEW_SHOPPER;
    case 3:
    case "PRODUCT_ITEM_METADATA_TYPE_BUNDLE":
      return ProductItemMetadataType.PRODUCT_ITEM_METADATA_TYPE_BUNDLE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProductItemMetadataType.UNRECOGNIZED;
  }
}

export function productItemMetadataTypeToJSON(object: ProductItemMetadataType): string {
  switch (object) {
    case ProductItemMetadataType.PRODUCT_ITEM_METADATA_TYPE_UNSPECIFIED:
      return "PRODUCT_ITEM_METADATA_TYPE_UNSPECIFIED";
    case ProductItemMetadataType.PRODUCT_ITEM_METADATA_TYPE_COUPON:
      return "PRODUCT_ITEM_METADATA_TYPE_COUPON";
    case ProductItemMetadataType.PRODUCT_ITEM_METADATA_TYPE_NEW_SHOPPER:
      return "PRODUCT_ITEM_METADATA_TYPE_NEW_SHOPPER";
    case ProductItemMetadataType.PRODUCT_ITEM_METADATA_TYPE_BUNDLE:
      return "PRODUCT_ITEM_METADATA_TYPE_BUNDLE";
    case ProductItemMetadataType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ProductPrice {
  amount: number;
  formatted: string;
  discountPrice?: number | undefined;
  saveAmount?: string | undefined;
  savePercentage?: string | undefined;
}

export interface ProductShippingInfo {
  free: boolean;
  method: ProductShippingMethod;
  origin: string;
  minEstimatedDays: number;
  maxEstimatedDays: number;
}

export interface ProductItemMetadata {
  type: ProductItemMetadataType;
  label: string;
}

export interface ProductsToLikeRequest {
  pagination?: PaginationRequest | undefined;
}

export interface ProductsToLikeResponse {
  data?: ProductsToLikeResponseData | undefined;
  error?: AppError | undefined;
}

export interface ProductsToLikeResponseData {
  products: ProductToLikeListItem[];
  pagination?: PaginationResponse | undefined;
}

export interface ProductToLikeListItem {
  id: string;
  title: string;
  image: string;
  price?: ProductPrice | undefined;
  rating?: number | undefined;
  sold?: number | undefined;
  meta: ProductItemMetadata[];
  variantId: string;
}

function createBaseProductPrice(): ProductPrice {
  return { amount: 0, formatted: "", discountPrice: undefined, saveAmount: undefined, savePercentage: undefined };
}

export const ProductPrice: MessageFns<ProductPrice> = {
  encode(message: ProductPrice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== 0) {
      writer.uint32(9).double(message.amount);
    }
    if (message.formatted !== "") {
      writer.uint32(18).string(message.formatted);
    }
    if (message.discountPrice !== undefined) {
      writer.uint32(25).double(message.discountPrice);
    }
    if (message.saveAmount !== undefined) {
      writer.uint32(34).string(message.saveAmount);
    }
    if (message.savePercentage !== undefined) {
      writer.uint32(42).string(message.savePercentage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductPrice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductPrice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.formatted = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.discountPrice = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.saveAmount = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.savePercentage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductPrice {
    return {
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      formatted: isSet(object.formatted) ? globalThis.String(object.formatted) : "",
      discountPrice: isSet(object.discountPrice) ? globalThis.Number(object.discountPrice) : undefined,
      saveAmount: isSet(object.saveAmount) ? globalThis.String(object.saveAmount) : undefined,
      savePercentage: isSet(object.savePercentage) ? globalThis.String(object.savePercentage) : undefined,
    };
  },

  toJSON(message: ProductPrice): unknown {
    const obj: any = {};
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.formatted !== "") {
      obj.formatted = message.formatted;
    }
    if (message.discountPrice !== undefined) {
      obj.discountPrice = message.discountPrice;
    }
    if (message.saveAmount !== undefined) {
      obj.saveAmount = message.saveAmount;
    }
    if (message.savePercentage !== undefined) {
      obj.savePercentage = message.savePercentage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductPrice>, I>>(base?: I): ProductPrice {
    return ProductPrice.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductPrice>, I>>(object: I): ProductPrice {
    const message = createBaseProductPrice();
    message.amount = object.amount ?? 0;
    message.formatted = object.formatted ?? "";
    message.discountPrice = object.discountPrice ?? undefined;
    message.saveAmount = object.saveAmount ?? undefined;
    message.savePercentage = object.savePercentage ?? undefined;
    return message;
  },
};

function createBaseProductShippingInfo(): ProductShippingInfo {
  return { free: false, method: 0, origin: "", minEstimatedDays: 0, maxEstimatedDays: 0 };
}

export const ProductShippingInfo: MessageFns<ProductShippingInfo> = {
  encode(message: ProductShippingInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.free !== false) {
      writer.uint32(8).bool(message.free);
    }
    if (message.method !== 0) {
      writer.uint32(16).int32(message.method);
    }
    if (message.origin !== "") {
      writer.uint32(26).string(message.origin);
    }
    if (message.minEstimatedDays !== 0) {
      writer.uint32(32).int32(message.minEstimatedDays);
    }
    if (message.maxEstimatedDays !== 0) {
      writer.uint32(40).int32(message.maxEstimatedDays);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductShippingInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductShippingInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.free = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.method = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.origin = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.minEstimatedDays = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.maxEstimatedDays = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductShippingInfo {
    return {
      free: isSet(object.free) ? globalThis.Boolean(object.free) : false,
      method: isSet(object.method) ? productShippingMethodFromJSON(object.method) : 0,
      origin: isSet(object.origin) ? globalThis.String(object.origin) : "",
      minEstimatedDays: isSet(object.minEstimatedDays) ? globalThis.Number(object.minEstimatedDays) : 0,
      maxEstimatedDays: isSet(object.maxEstimatedDays) ? globalThis.Number(object.maxEstimatedDays) : 0,
    };
  },

  toJSON(message: ProductShippingInfo): unknown {
    const obj: any = {};
    if (message.free !== false) {
      obj.free = message.free;
    }
    if (message.method !== 0) {
      obj.method = productShippingMethodToJSON(message.method);
    }
    if (message.origin !== "") {
      obj.origin = message.origin;
    }
    if (message.minEstimatedDays !== 0) {
      obj.minEstimatedDays = Math.round(message.minEstimatedDays);
    }
    if (message.maxEstimatedDays !== 0) {
      obj.maxEstimatedDays = Math.round(message.maxEstimatedDays);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductShippingInfo>, I>>(base?: I): ProductShippingInfo {
    return ProductShippingInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductShippingInfo>, I>>(object: I): ProductShippingInfo {
    const message = createBaseProductShippingInfo();
    message.free = object.free ?? false;
    message.method = object.method ?? 0;
    message.origin = object.origin ?? "";
    message.minEstimatedDays = object.minEstimatedDays ?? 0;
    message.maxEstimatedDays = object.maxEstimatedDays ?? 0;
    return message;
  },
};

function createBaseProductItemMetadata(): ProductItemMetadata {
  return { type: 0, label: "" };
}

export const ProductItemMetadata: MessageFns<ProductItemMetadata> = {
  encode(message: ProductItemMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.label !== "") {
      writer.uint32(18).string(message.label);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductItemMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductItemMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.label = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductItemMetadata {
    return {
      type: isSet(object.type) ? productItemMetadataTypeFromJSON(object.type) : 0,
      label: isSet(object.label) ? globalThis.String(object.label) : "",
    };
  },

  toJSON(message: ProductItemMetadata): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = productItemMetadataTypeToJSON(message.type);
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductItemMetadata>, I>>(base?: I): ProductItemMetadata {
    return ProductItemMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductItemMetadata>, I>>(object: I): ProductItemMetadata {
    const message = createBaseProductItemMetadata();
    message.type = object.type ?? 0;
    message.label = object.label ?? "";
    return message;
  },
};

function createBaseProductsToLikeRequest(): ProductsToLikeRequest {
  return { pagination: undefined };
}

export const ProductsToLikeRequest: MessageFns<ProductsToLikeRequest> = {
  encode(message: ProductsToLikeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PaginationRequest.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductsToLikeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductsToLikeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PaginationRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductsToLikeRequest {
    return { pagination: isSet(object.pagination) ? PaginationRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: ProductsToLikeRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PaginationRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductsToLikeRequest>, I>>(base?: I): ProductsToLikeRequest {
    return ProductsToLikeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductsToLikeRequest>, I>>(object: I): ProductsToLikeRequest {
    const message = createBaseProductsToLikeRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PaginationRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseProductsToLikeResponse(): ProductsToLikeResponse {
  return { data: undefined, error: undefined };
}

export const ProductsToLikeResponse: MessageFns<ProductsToLikeResponse> = {
  encode(message: ProductsToLikeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      ProductsToLikeResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductsToLikeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductsToLikeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = ProductsToLikeResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductsToLikeResponse {
    return {
      data: isSet(object.data) ? ProductsToLikeResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: ProductsToLikeResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = ProductsToLikeResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductsToLikeResponse>, I>>(base?: I): ProductsToLikeResponse {
    return ProductsToLikeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductsToLikeResponse>, I>>(object: I): ProductsToLikeResponse {
    const message = createBaseProductsToLikeResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? ProductsToLikeResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseProductsToLikeResponseData(): ProductsToLikeResponseData {
  return { products: [], pagination: undefined };
}

export const ProductsToLikeResponseData: MessageFns<ProductsToLikeResponseData> = {
  encode(message: ProductsToLikeResponseData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.products) {
      ProductToLikeListItem.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PaginationResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductsToLikeResponseData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductsToLikeResponseData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.products.push(ProductToLikeListItem.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PaginationResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductsToLikeResponseData {
    return {
      products: globalThis.Array.isArray(object?.products)
        ? object.products.map((e: any) => ProductToLikeListItem.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PaginationResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: ProductsToLikeResponseData): unknown {
    const obj: any = {};
    if (message.products?.length) {
      obj.products = message.products.map((e) => ProductToLikeListItem.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PaginationResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductsToLikeResponseData>, I>>(base?: I): ProductsToLikeResponseData {
    return ProductsToLikeResponseData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductsToLikeResponseData>, I>>(object: I): ProductsToLikeResponseData {
    const message = createBaseProductsToLikeResponseData();
    message.products = object.products?.map((e) => ProductToLikeListItem.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PaginationResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseProductToLikeListItem(): ProductToLikeListItem {
  return {
    id: "",
    title: "",
    image: "",
    price: undefined,
    rating: undefined,
    sold: undefined,
    meta: [],
    variantId: "",
  };
}

export const ProductToLikeListItem: MessageFns<ProductToLikeListItem> = {
  encode(message: ProductToLikeListItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.image !== "") {
      writer.uint32(26).string(message.image);
    }
    if (message.price !== undefined) {
      ProductPrice.encode(message.price, writer.uint32(34).fork()).join();
    }
    if (message.rating !== undefined) {
      writer.uint32(41).double(message.rating);
    }
    if (message.sold !== undefined) {
      writer.uint32(48).int32(message.sold);
    }
    for (const v of message.meta) {
      ProductItemMetadata.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.variantId !== "") {
      writer.uint32(66).string(message.variantId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductToLikeListItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductToLikeListItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.image = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.price = ProductPrice.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.rating = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.sold = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.meta.push(ProductItemMetadata.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.variantId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductToLikeListItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      image: isSet(object.image) ? globalThis.String(object.image) : "",
      price: isSet(object.price) ? ProductPrice.fromJSON(object.price) : undefined,
      rating: isSet(object.rating) ? globalThis.Number(object.rating) : undefined,
      sold: isSet(object.sold) ? globalThis.Number(object.sold) : undefined,
      meta: globalThis.Array.isArray(object?.meta) ? object.meta.map((e: any) => ProductItemMetadata.fromJSON(e)) : [],
      variantId: isSet(object.variantId) ? globalThis.String(object.variantId) : "",
    };
  },

  toJSON(message: ProductToLikeListItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.image !== "") {
      obj.image = message.image;
    }
    if (message.price !== undefined) {
      obj.price = ProductPrice.toJSON(message.price);
    }
    if (message.rating !== undefined) {
      obj.rating = message.rating;
    }
    if (message.sold !== undefined) {
      obj.sold = Math.round(message.sold);
    }
    if (message.meta?.length) {
      obj.meta = message.meta.map((e) => ProductItemMetadata.toJSON(e));
    }
    if (message.variantId !== "") {
      obj.variantId = message.variantId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductToLikeListItem>, I>>(base?: I): ProductToLikeListItem {
    return ProductToLikeListItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductToLikeListItem>, I>>(object: I): ProductToLikeListItem {
    const message = createBaseProductToLikeListItem();
    message.id = object.id ?? "";
    message.title = object.title ?? "";
    message.image = object.image ?? "";
    message.price = (object.price !== undefined && object.price !== null)
      ? ProductPrice.fromPartial(object.price)
      : undefined;
    message.rating = object.rating ?? undefined;
    message.sold = object.sold ?? undefined;
    message.meta = object.meta?.map((e) => ProductItemMetadata.fromPartial(e)) || [];
    message.variantId = object.variantId ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
