// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: products/v1/products.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { BestSellingProductsRequest, BestSellingProductsResponse } from "./best_selling_products";
import { BigDiscountProductsRequest, BigDiscountProductsResponse } from "./big_discount_products";
import { HeroProductsRequest, HeroProductsResponse } from "./hero_products";
import { NewlyAddedProductsRequest, NewlyAddedProductsResponse } from "./newly_added_products";
import { ProductCreateRequest, ProductCreateResponse } from "./product_create";
import { ProductDataRequest, ProductDataResponse } from "./product_data";
import { ProductSnapshotRequest, ProductSnapshotResponse } from "./product_snapshot";
import { ProductsToLikeRequest, ProductsToLikeResponse } from "./products_to_like";

export const protobufPackage = "products.v1";

export type ProductsServiceService = typeof ProductsServiceService;
export const ProductsServiceService = {
  productCreate: {
    path: "/products.v1.ProductsService/ProductCreate",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ProductCreateRequest): Buffer => Buffer.from(ProductCreateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ProductCreateRequest => ProductCreateRequest.decode(value),
    responseSerialize: (value: ProductCreateResponse): Buffer =>
      Buffer.from(ProductCreateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ProductCreateResponse => ProductCreateResponse.decode(value),
  },
  productData: {
    path: "/products.v1.ProductsService/ProductData",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ProductDataRequest): Buffer => Buffer.from(ProductDataRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ProductDataRequest => ProductDataRequest.decode(value),
    responseSerialize: (value: ProductDataResponse): Buffer => Buffer.from(ProductDataResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ProductDataResponse => ProductDataResponse.decode(value),
  },
  productsToLike: {
    path: "/products.v1.ProductsService/ProductsToLike",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ProductsToLikeRequest): Buffer =>
      Buffer.from(ProductsToLikeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ProductsToLikeRequest => ProductsToLikeRequest.decode(value),
    responseSerialize: (value: ProductsToLikeResponse): Buffer =>
      Buffer.from(ProductsToLikeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ProductsToLikeResponse => ProductsToLikeResponse.decode(value),
  },
  productSnapshot: {
    path: "/products.v1.ProductsService/ProductSnapshot",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ProductSnapshotRequest): Buffer =>
      Buffer.from(ProductSnapshotRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ProductSnapshotRequest => ProductSnapshotRequest.decode(value),
    responseSerialize: (value: ProductSnapshotResponse): Buffer =>
      Buffer.from(ProductSnapshotResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ProductSnapshotResponse => ProductSnapshotResponse.decode(value),
  },
  bestSellingProducts: {
    path: "/products.v1.ProductsService/BestSellingProducts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: BestSellingProductsRequest): Buffer =>
      Buffer.from(BestSellingProductsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): BestSellingProductsRequest => BestSellingProductsRequest.decode(value),
    responseSerialize: (value: BestSellingProductsResponse): Buffer =>
      Buffer.from(BestSellingProductsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BestSellingProductsResponse => BestSellingProductsResponse.decode(value),
  },
  bigDiscountProducts: {
    path: "/products.v1.ProductsService/BigDiscountProducts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: BigDiscountProductsRequest): Buffer =>
      Buffer.from(BigDiscountProductsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): BigDiscountProductsRequest => BigDiscountProductsRequest.decode(value),
    responseSerialize: (value: BigDiscountProductsResponse): Buffer =>
      Buffer.from(BigDiscountProductsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BigDiscountProductsResponse => BigDiscountProductsResponse.decode(value),
  },
  newlyAddedProducts: {
    path: "/products.v1.ProductsService/NewlyAddedProducts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: NewlyAddedProductsRequest): Buffer =>
      Buffer.from(NewlyAddedProductsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): NewlyAddedProductsRequest => NewlyAddedProductsRequest.decode(value),
    responseSerialize: (value: NewlyAddedProductsResponse): Buffer =>
      Buffer.from(NewlyAddedProductsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): NewlyAddedProductsResponse => NewlyAddedProductsResponse.decode(value),
  },
  heroProducts: {
    path: "/products.v1.ProductsService/HeroProducts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: HeroProductsRequest): Buffer => Buffer.from(HeroProductsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HeroProductsRequest => HeroProductsRequest.decode(value),
    responseSerialize: (value: HeroProductsResponse): Buffer =>
      Buffer.from(HeroProductsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HeroProductsResponse => HeroProductsResponse.decode(value),
  },
} as const;

export interface ProductsServiceServer extends UntypedServiceImplementation {
  productCreate: handleUnaryCall<ProductCreateRequest, ProductCreateResponse>;
  productData: handleUnaryCall<ProductDataRequest, ProductDataResponse>;
  productsToLike: handleUnaryCall<ProductsToLikeRequest, ProductsToLikeResponse>;
  productSnapshot: handleUnaryCall<ProductSnapshotRequest, ProductSnapshotResponse>;
  bestSellingProducts: handleUnaryCall<BestSellingProductsRequest, BestSellingProductsResponse>;
  bigDiscountProducts: handleUnaryCall<BigDiscountProductsRequest, BigDiscountProductsResponse>;
  newlyAddedProducts: handleUnaryCall<NewlyAddedProductsRequest, NewlyAddedProductsResponse>;
  heroProducts: handleUnaryCall<HeroProductsRequest, HeroProductsResponse>;
}

export interface ProductsServiceClient extends Client {
  productCreate(
    request: ProductCreateRequest,
    callback: (error: ServiceError | null, response: ProductCreateResponse) => void,
  ): ClientUnaryCall;
  productCreate(
    request: ProductCreateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ProductCreateResponse) => void,
  ): ClientUnaryCall;
  productCreate(
    request: ProductCreateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ProductCreateResponse) => void,
  ): ClientUnaryCall;
  productData(
    request: ProductDataRequest,
    callback: (error: ServiceError | null, response: ProductDataResponse) => void,
  ): ClientUnaryCall;
  productData(
    request: ProductDataRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ProductDataResponse) => void,
  ): ClientUnaryCall;
  productData(
    request: ProductDataRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ProductDataResponse) => void,
  ): ClientUnaryCall;
  productsToLike(
    request: ProductsToLikeRequest,
    callback: (error: ServiceError | null, response: ProductsToLikeResponse) => void,
  ): ClientUnaryCall;
  productsToLike(
    request: ProductsToLikeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ProductsToLikeResponse) => void,
  ): ClientUnaryCall;
  productsToLike(
    request: ProductsToLikeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ProductsToLikeResponse) => void,
  ): ClientUnaryCall;
  productSnapshot(
    request: ProductSnapshotRequest,
    callback: (error: ServiceError | null, response: ProductSnapshotResponse) => void,
  ): ClientUnaryCall;
  productSnapshot(
    request: ProductSnapshotRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ProductSnapshotResponse) => void,
  ): ClientUnaryCall;
  productSnapshot(
    request: ProductSnapshotRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ProductSnapshotResponse) => void,
  ): ClientUnaryCall;
  bestSellingProducts(
    request: BestSellingProductsRequest,
    callback: (error: ServiceError | null, response: BestSellingProductsResponse) => void,
  ): ClientUnaryCall;
  bestSellingProducts(
    request: BestSellingProductsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BestSellingProductsResponse) => void,
  ): ClientUnaryCall;
  bestSellingProducts(
    request: BestSellingProductsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BestSellingProductsResponse) => void,
  ): ClientUnaryCall;
  bigDiscountProducts(
    request: BigDiscountProductsRequest,
    callback: (error: ServiceError | null, response: BigDiscountProductsResponse) => void,
  ): ClientUnaryCall;
  bigDiscountProducts(
    request: BigDiscountProductsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BigDiscountProductsResponse) => void,
  ): ClientUnaryCall;
  bigDiscountProducts(
    request: BigDiscountProductsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BigDiscountProductsResponse) => void,
  ): ClientUnaryCall;
  newlyAddedProducts(
    request: NewlyAddedProductsRequest,
    callback: (error: ServiceError | null, response: NewlyAddedProductsResponse) => void,
  ): ClientUnaryCall;
  newlyAddedProducts(
    request: NewlyAddedProductsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: NewlyAddedProductsResponse) => void,
  ): ClientUnaryCall;
  newlyAddedProducts(
    request: NewlyAddedProductsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: NewlyAddedProductsResponse) => void,
  ): ClientUnaryCall;
  heroProducts(
    request: HeroProductsRequest,
    callback: (error: ServiceError | null, response: HeroProductsResponse) => void,
  ): ClientUnaryCall;
  heroProducts(
    request: HeroProductsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HeroProductsResponse) => void,
  ): ClientUnaryCall;
  heroProducts(
    request: HeroProductsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HeroProductsResponse) => void,
  ): ClientUnaryCall;
}

export const ProductsServiceClient = makeGenericClientConstructor(
  ProductsServiceService,
  "products.v1.ProductsService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ProductsServiceClient;
  service: typeof ProductsServiceService;
  serviceName: string;
};
