// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: inventory/v1/inventory_reserve.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error.js";
import {
  InventoryReservationListItem,
  InventoryReservationStatus,
  inventoryReservationStatusFromJSON,
  inventoryReservationStatusToJSON,
} from "./reservation_get.js";

export const protobufPackage = "inventory.v1";

/** Request/Response for inventory reservation */
export interface InventoryReserveRequest {
  orderId: string;
  items: InventoryReserveRequestItem[];
  /** Time to live for reservation */
  ttlSeconds: string;
}

export interface InventoryReserveRequestItem {
  productId: string;
  /** Optional if product has no variations */
  variantId: string;
  sku: string;
  quantity: number;
}

export interface InventoryReserveResponse {
  data?: InventoryReserveResponseData | undefined;
  error?: AppError | undefined;
}

export interface InventoryReserveResponseData {
  reservationToken: string;
  status: InventoryReservationStatus;
  items: InventoryReservationListItem[];
}

function createBaseInventoryReserveRequest(): InventoryReserveRequest {
  return { orderId: "", items: [], ttlSeconds: "0" };
}

export const InventoryReserveRequest: MessageFns<InventoryReserveRequest> = {
  encode(message: InventoryReserveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    for (const v of message.items) {
      InventoryReserveRequestItem.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.ttlSeconds !== "0") {
      writer.uint32(24).int64(message.ttlSeconds);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InventoryReserveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInventoryReserveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.items.push(InventoryReserveRequestItem.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.ttlSeconds = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InventoryReserveRequest {
    return {
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => InventoryReserveRequestItem.fromJSON(e))
        : [],
      ttlSeconds: isSet(object.ttlSeconds) ? globalThis.String(object.ttlSeconds) : "0",
    };
  },

  toJSON(message: InventoryReserveRequest): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => InventoryReserveRequestItem.toJSON(e));
    }
    if (message.ttlSeconds !== "0") {
      obj.ttlSeconds = message.ttlSeconds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InventoryReserveRequest>, I>>(base?: I): InventoryReserveRequest {
    return InventoryReserveRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InventoryReserveRequest>, I>>(object: I): InventoryReserveRequest {
    const message = createBaseInventoryReserveRequest();
    message.orderId = object.orderId ?? "";
    message.items = object.items?.map((e) => InventoryReserveRequestItem.fromPartial(e)) || [];
    message.ttlSeconds = object.ttlSeconds ?? "0";
    return message;
  },
};

function createBaseInventoryReserveRequestItem(): InventoryReserveRequestItem {
  return { productId: "", variantId: "", sku: "", quantity: 0 };
}

export const InventoryReserveRequestItem: MessageFns<InventoryReserveRequestItem> = {
  encode(message: InventoryReserveRequestItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    if (message.variantId !== "") {
      writer.uint32(18).string(message.variantId);
    }
    if (message.sku !== "") {
      writer.uint32(26).string(message.sku);
    }
    if (message.quantity !== 0) {
      writer.uint32(32).uint32(message.quantity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InventoryReserveRequestItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInventoryReserveRequestItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.variantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sku = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.quantity = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InventoryReserveRequestItem {
    return {
      productId: isSet(object.productId) ? globalThis.String(object.productId) : "",
      variantId: isSet(object.variantId) ? globalThis.String(object.variantId) : "",
      sku: isSet(object.sku) ? globalThis.String(object.sku) : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
    };
  },

  toJSON(message: InventoryReserveRequestItem): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.variantId !== "") {
      obj.variantId = message.variantId;
    }
    if (message.sku !== "") {
      obj.sku = message.sku;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InventoryReserveRequestItem>, I>>(base?: I): InventoryReserveRequestItem {
    return InventoryReserveRequestItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InventoryReserveRequestItem>, I>>(object: I): InventoryReserveRequestItem {
    const message = createBaseInventoryReserveRequestItem();
    message.productId = object.productId ?? "";
    message.variantId = object.variantId ?? "";
    message.sku = object.sku ?? "";
    message.quantity = object.quantity ?? 0;
    return message;
  },
};

function createBaseInventoryReserveResponse(): InventoryReserveResponse {
  return { data: undefined, error: undefined };
}

export const InventoryReserveResponse: MessageFns<InventoryReserveResponse> = {
  encode(message: InventoryReserveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      InventoryReserveResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InventoryReserveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInventoryReserveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = InventoryReserveResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InventoryReserveResponse {
    return {
      data: isSet(object.data) ? InventoryReserveResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: InventoryReserveResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = InventoryReserveResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InventoryReserveResponse>, I>>(base?: I): InventoryReserveResponse {
    return InventoryReserveResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InventoryReserveResponse>, I>>(object: I): InventoryReserveResponse {
    const message = createBaseInventoryReserveResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? InventoryReserveResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseInventoryReserveResponseData(): InventoryReserveResponseData {
  return { reservationToken: "", status: 0, items: [] };
}

export const InventoryReserveResponseData: MessageFns<InventoryReserveResponseData> = {
  encode(message: InventoryReserveResponseData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reservationToken !== "") {
      writer.uint32(10).string(message.reservationToken);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    for (const v of message.items) {
      InventoryReservationListItem.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InventoryReserveResponseData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInventoryReserveResponseData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reservationToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.items.push(InventoryReservationListItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InventoryReserveResponseData {
    return {
      reservationToken: isSet(object.reservationToken) ? globalThis.String(object.reservationToken) : "",
      status: isSet(object.status) ? inventoryReservationStatusFromJSON(object.status) : 0,
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => InventoryReservationListItem.fromJSON(e))
        : [],
    };
  },

  toJSON(message: InventoryReserveResponseData): unknown {
    const obj: any = {};
    if (message.reservationToken !== "") {
      obj.reservationToken = message.reservationToken;
    }
    if (message.status !== 0) {
      obj.status = inventoryReservationStatusToJSON(message.status);
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => InventoryReservationListItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InventoryReserveResponseData>, I>>(base?: I): InventoryReserveResponseData {
    return InventoryReserveResponseData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InventoryReserveResponseData>, I>>(object: I): InventoryReserveResponseData {
    const message = createBaseInventoryReserveResponseData();
    message.reservationToken = object.reservationToken ?? "";
    message.status = object.status ?? 0;
    message.items = object.items?.map((e) => InventoryReservationListItem.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
