// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: products/v1/hero_products.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error.js";
import { Struct } from "../../shared/v1/struct.js";

export const protobufPackage = "products.v1";

export interface HeroProduct {
  id: string;
  productsData?: Struct | undefined;
  createdAt: string;
  updatedAt?: string | undefined;
}

export interface HeroProductData {
  categorySlider?: CategorySlider | undefined;
  welcomeDealsSlider?: WelcomeDealsSlider | undefined;
}

export interface HeroProductsRequest {
}

export interface HeroProductsResponse {
  data?: HeroProductsResponseData | undefined;
  error?: AppError | undefined;
}

export interface HeroProductsResponseData {
  categorySlider?: CategorySlider | undefined;
  welcomeDealsSlider?: WelcomeDealsSlider | undefined;
}

export interface CategorySlider {
  title: string;
  subtitle: string;
  buttonText: string;
  products: HeroProductListItem[];
}

export interface WelcomeDealsSlider {
  title: string;
  subtitle: string;
  buttonText: string;
  products: HeroProductListItem[];
}

export interface HeroProductListItem {
  /** product id */
  id: string;
  variantId: string;
}

function createBaseHeroProduct(): HeroProduct {
  return { id: "", productsData: undefined, createdAt: "0", updatedAt: undefined };
}

export const HeroProduct: MessageFns<HeroProduct> = {
  encode(message: HeroProduct, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.productsData !== undefined) {
      Struct.encode(message.productsData, writer.uint32(18).fork()).join();
    }
    if (message.createdAt !== "0") {
      writer.uint32(24).uint64(message.createdAt);
    }
    if (message.updatedAt !== undefined) {
      writer.uint32(32).uint64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeroProduct {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeroProduct();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.productsData = Struct.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.createdAt = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.updatedAt = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeroProduct {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      productsData: isSet(object.productsData) ? Struct.fromJSON(object.productsData) : undefined,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "0",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : undefined,
    };
  },

  toJSON(message: HeroProduct): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.productsData !== undefined) {
      obj.productsData = Struct.toJSON(message.productsData);
    }
    if (message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeroProduct>, I>>(base?: I): HeroProduct {
    return HeroProduct.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeroProduct>, I>>(object: I): HeroProduct {
    const message = createBaseHeroProduct();
    message.id = object.id ?? "";
    message.productsData = (object.productsData !== undefined && object.productsData !== null)
      ? Struct.fromPartial(object.productsData)
      : undefined;
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseHeroProductData(): HeroProductData {
  return { categorySlider: undefined, welcomeDealsSlider: undefined };
}

export const HeroProductData: MessageFns<HeroProductData> = {
  encode(message: HeroProductData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.categorySlider !== undefined) {
      CategorySlider.encode(message.categorySlider, writer.uint32(10).fork()).join();
    }
    if (message.welcomeDealsSlider !== undefined) {
      WelcomeDealsSlider.encode(message.welcomeDealsSlider, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeroProductData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeroProductData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.categorySlider = CategorySlider.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.welcomeDealsSlider = WelcomeDealsSlider.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeroProductData {
    return {
      categorySlider: isSet(object.categorySlider) ? CategorySlider.fromJSON(object.categorySlider) : undefined,
      welcomeDealsSlider: isSet(object.welcomeDealsSlider)
        ? WelcomeDealsSlider.fromJSON(object.welcomeDealsSlider)
        : undefined,
    };
  },

  toJSON(message: HeroProductData): unknown {
    const obj: any = {};
    if (message.categorySlider !== undefined) {
      obj.categorySlider = CategorySlider.toJSON(message.categorySlider);
    }
    if (message.welcomeDealsSlider !== undefined) {
      obj.welcomeDealsSlider = WelcomeDealsSlider.toJSON(message.welcomeDealsSlider);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeroProductData>, I>>(base?: I): HeroProductData {
    return HeroProductData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeroProductData>, I>>(object: I): HeroProductData {
    const message = createBaseHeroProductData();
    message.categorySlider = (object.categorySlider !== undefined && object.categorySlider !== null)
      ? CategorySlider.fromPartial(object.categorySlider)
      : undefined;
    message.welcomeDealsSlider = (object.welcomeDealsSlider !== undefined && object.welcomeDealsSlider !== null)
      ? WelcomeDealsSlider.fromPartial(object.welcomeDealsSlider)
      : undefined;
    return message;
  },
};

function createBaseHeroProductsRequest(): HeroProductsRequest {
  return {};
}

export const HeroProductsRequest: MessageFns<HeroProductsRequest> = {
  encode(_: HeroProductsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeroProductsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeroProductsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): HeroProductsRequest {
    return {};
  },

  toJSON(_: HeroProductsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<HeroProductsRequest>, I>>(base?: I): HeroProductsRequest {
    return HeroProductsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeroProductsRequest>, I>>(_: I): HeroProductsRequest {
    const message = createBaseHeroProductsRequest();
    return message;
  },
};

function createBaseHeroProductsResponse(): HeroProductsResponse {
  return { data: undefined, error: undefined };
}

export const HeroProductsResponse: MessageFns<HeroProductsResponse> = {
  encode(message: HeroProductsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      HeroProductsResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeroProductsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeroProductsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = HeroProductsResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeroProductsResponse {
    return {
      data: isSet(object.data) ? HeroProductsResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: HeroProductsResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = HeroProductsResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeroProductsResponse>, I>>(base?: I): HeroProductsResponse {
    return HeroProductsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeroProductsResponse>, I>>(object: I): HeroProductsResponse {
    const message = createBaseHeroProductsResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? HeroProductsResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseHeroProductsResponseData(): HeroProductsResponseData {
  return { categorySlider: undefined, welcomeDealsSlider: undefined };
}

export const HeroProductsResponseData: MessageFns<HeroProductsResponseData> = {
  encode(message: HeroProductsResponseData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.categorySlider !== undefined) {
      CategorySlider.encode(message.categorySlider, writer.uint32(10).fork()).join();
    }
    if (message.welcomeDealsSlider !== undefined) {
      WelcomeDealsSlider.encode(message.welcomeDealsSlider, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeroProductsResponseData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeroProductsResponseData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.categorySlider = CategorySlider.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.welcomeDealsSlider = WelcomeDealsSlider.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeroProductsResponseData {
    return {
      categorySlider: isSet(object.categorySlider) ? CategorySlider.fromJSON(object.categorySlider) : undefined,
      welcomeDealsSlider: isSet(object.welcomeDealsSlider)
        ? WelcomeDealsSlider.fromJSON(object.welcomeDealsSlider)
        : undefined,
    };
  },

  toJSON(message: HeroProductsResponseData): unknown {
    const obj: any = {};
    if (message.categorySlider !== undefined) {
      obj.categorySlider = CategorySlider.toJSON(message.categorySlider);
    }
    if (message.welcomeDealsSlider !== undefined) {
      obj.welcomeDealsSlider = WelcomeDealsSlider.toJSON(message.welcomeDealsSlider);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeroProductsResponseData>, I>>(base?: I): HeroProductsResponseData {
    return HeroProductsResponseData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeroProductsResponseData>, I>>(object: I): HeroProductsResponseData {
    const message = createBaseHeroProductsResponseData();
    message.categorySlider = (object.categorySlider !== undefined && object.categorySlider !== null)
      ? CategorySlider.fromPartial(object.categorySlider)
      : undefined;
    message.welcomeDealsSlider = (object.welcomeDealsSlider !== undefined && object.welcomeDealsSlider !== null)
      ? WelcomeDealsSlider.fromPartial(object.welcomeDealsSlider)
      : undefined;
    return message;
  },
};

function createBaseCategorySlider(): CategorySlider {
  return { title: "", subtitle: "", buttonText: "", products: [] };
}

export const CategorySlider: MessageFns<CategorySlider> = {
  encode(message: CategorySlider, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.subtitle !== "") {
      writer.uint32(18).string(message.subtitle);
    }
    if (message.buttonText !== "") {
      writer.uint32(26).string(message.buttonText);
    }
    for (const v of message.products) {
      HeroProductListItem.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CategorySlider {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCategorySlider();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subtitle = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.buttonText = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.products.push(HeroProductListItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CategorySlider {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      subtitle: isSet(object.subtitle) ? globalThis.String(object.subtitle) : "",
      buttonText: isSet(object.buttonText) ? globalThis.String(object.buttonText) : "",
      products: globalThis.Array.isArray(object?.products)
        ? object.products.map((e: any) => HeroProductListItem.fromJSON(e))
        : [],
    };
  },

  toJSON(message: CategorySlider): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.subtitle !== "") {
      obj.subtitle = message.subtitle;
    }
    if (message.buttonText !== "") {
      obj.buttonText = message.buttonText;
    }
    if (message.products?.length) {
      obj.products = message.products.map((e) => HeroProductListItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CategorySlider>, I>>(base?: I): CategorySlider {
    return CategorySlider.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CategorySlider>, I>>(object: I): CategorySlider {
    const message = createBaseCategorySlider();
    message.title = object.title ?? "";
    message.subtitle = object.subtitle ?? "";
    message.buttonText = object.buttonText ?? "";
    message.products = object.products?.map((e) => HeroProductListItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseWelcomeDealsSlider(): WelcomeDealsSlider {
  return { title: "", subtitle: "", buttonText: "", products: [] };
}

export const WelcomeDealsSlider: MessageFns<WelcomeDealsSlider> = {
  encode(message: WelcomeDealsSlider, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.subtitle !== "") {
      writer.uint32(18).string(message.subtitle);
    }
    if (message.buttonText !== "") {
      writer.uint32(26).string(message.buttonText);
    }
    for (const v of message.products) {
      HeroProductListItem.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WelcomeDealsSlider {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWelcomeDealsSlider();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subtitle = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.buttonText = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.products.push(HeroProductListItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WelcomeDealsSlider {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      subtitle: isSet(object.subtitle) ? globalThis.String(object.subtitle) : "",
      buttonText: isSet(object.buttonText) ? globalThis.String(object.buttonText) : "",
      products: globalThis.Array.isArray(object?.products)
        ? object.products.map((e: any) => HeroProductListItem.fromJSON(e))
        : [],
    };
  },

  toJSON(message: WelcomeDealsSlider): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.subtitle !== "") {
      obj.subtitle = message.subtitle;
    }
    if (message.buttonText !== "") {
      obj.buttonText = message.buttonText;
    }
    if (message.products?.length) {
      obj.products = message.products.map((e) => HeroProductListItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WelcomeDealsSlider>, I>>(base?: I): WelcomeDealsSlider {
    return WelcomeDealsSlider.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WelcomeDealsSlider>, I>>(object: I): WelcomeDealsSlider {
    const message = createBaseWelcomeDealsSlider();
    message.title = object.title ?? "";
    message.subtitle = object.subtitle ?? "";
    message.buttonText = object.buttonText ?? "";
    message.products = object.products?.map((e) => HeroProductListItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseHeroProductListItem(): HeroProductListItem {
  return { id: "", variantId: "" };
}

export const HeroProductListItem: MessageFns<HeroProductListItem> = {
  encode(message: HeroProductListItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.variantId !== "") {
      writer.uint32(18).string(message.variantId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeroProductListItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeroProductListItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.variantId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeroProductListItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      variantId: isSet(object.variantId) ? globalThis.String(object.variantId) : "",
    };
  },

  toJSON(message: HeroProductListItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.variantId !== "") {
      obj.variantId = message.variantId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeroProductListItem>, I>>(base?: I): HeroProductListItem {
    return HeroProductListItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeroProductListItem>, I>>(object: I): HeroProductListItem {
    const message = createBaseHeroProductListItem();
    message.id = object.id ?? "";
    message.variantId = object.variantId ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
