// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: products/v1/newly_added_products.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error.js";

export const protobufPackage = "products.v1";

export interface NewlyAddedProductsRequest {
}

export interface NewlyAddedProductsResponse {
  data?: NewlyAddedProductsResponseData | undefined;
  error?: AppError | undefined;
}

export interface NewlyAddedProductsResponseData {
  products: NewlyAddedProductListItem[];
}

export interface NewlyAddedProductListItem {
  id: string;
  title: string;
  image: string;
  priceCents: number;
  salePriceCents?: number | undefined;
  discountPercentage?:
    | number
    | undefined;
  /** E.g. a string like: Added 1 hour ago */
  createdAt: string;
}

function createBaseNewlyAddedProductsRequest(): NewlyAddedProductsRequest {
  return {};
}

export const NewlyAddedProductsRequest: MessageFns<NewlyAddedProductsRequest> = {
  encode(_: NewlyAddedProductsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NewlyAddedProductsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNewlyAddedProductsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): NewlyAddedProductsRequest {
    return {};
  },

  toJSON(_: NewlyAddedProductsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<NewlyAddedProductsRequest>, I>>(base?: I): NewlyAddedProductsRequest {
    return NewlyAddedProductsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NewlyAddedProductsRequest>, I>>(_: I): NewlyAddedProductsRequest {
    const message = createBaseNewlyAddedProductsRequest();
    return message;
  },
};

function createBaseNewlyAddedProductsResponse(): NewlyAddedProductsResponse {
  return { data: undefined, error: undefined };
}

export const NewlyAddedProductsResponse: MessageFns<NewlyAddedProductsResponse> = {
  encode(message: NewlyAddedProductsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      NewlyAddedProductsResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NewlyAddedProductsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNewlyAddedProductsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = NewlyAddedProductsResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NewlyAddedProductsResponse {
    return {
      data: isSet(object.data) ? NewlyAddedProductsResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: NewlyAddedProductsResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = NewlyAddedProductsResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NewlyAddedProductsResponse>, I>>(base?: I): NewlyAddedProductsResponse {
    return NewlyAddedProductsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NewlyAddedProductsResponse>, I>>(object: I): NewlyAddedProductsResponse {
    const message = createBaseNewlyAddedProductsResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? NewlyAddedProductsResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseNewlyAddedProductsResponseData(): NewlyAddedProductsResponseData {
  return { products: [] };
}

export const NewlyAddedProductsResponseData: MessageFns<NewlyAddedProductsResponseData> = {
  encode(message: NewlyAddedProductsResponseData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.products) {
      NewlyAddedProductListItem.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NewlyAddedProductsResponseData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNewlyAddedProductsResponseData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.products.push(NewlyAddedProductListItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NewlyAddedProductsResponseData {
    return {
      products: globalThis.Array.isArray(object?.products)
        ? object.products.map((e: any) => NewlyAddedProductListItem.fromJSON(e))
        : [],
    };
  },

  toJSON(message: NewlyAddedProductsResponseData): unknown {
    const obj: any = {};
    if (message.products?.length) {
      obj.products = message.products.map((e) => NewlyAddedProductListItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NewlyAddedProductsResponseData>, I>>(base?: I): NewlyAddedProductsResponseData {
    return NewlyAddedProductsResponseData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NewlyAddedProductsResponseData>, I>>(
    object: I,
  ): NewlyAddedProductsResponseData {
    const message = createBaseNewlyAddedProductsResponseData();
    message.products = object.products?.map((e) => NewlyAddedProductListItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseNewlyAddedProductListItem(): NewlyAddedProductListItem {
  return {
    id: "",
    title: "",
    image: "",
    priceCents: 0,
    salePriceCents: undefined,
    discountPercentage: undefined,
    createdAt: "",
  };
}

export const NewlyAddedProductListItem: MessageFns<NewlyAddedProductListItem> = {
  encode(message: NewlyAddedProductListItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.image !== "") {
      writer.uint32(26).string(message.image);
    }
    if (message.priceCents !== 0) {
      writer.uint32(32).uint32(message.priceCents);
    }
    if (message.salePriceCents !== undefined) {
      writer.uint32(40).uint32(message.salePriceCents);
    }
    if (message.discountPercentage !== undefined) {
      writer.uint32(48).uint32(message.discountPercentage);
    }
    if (message.createdAt !== "") {
      writer.uint32(58).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NewlyAddedProductListItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNewlyAddedProductListItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.image = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.priceCents = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.salePriceCents = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.discountPercentage = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NewlyAddedProductListItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      image: isSet(object.image) ? globalThis.String(object.image) : "",
      priceCents: isSet(object.priceCents) ? globalThis.Number(object.priceCents) : 0,
      salePriceCents: isSet(object.salePriceCents) ? globalThis.Number(object.salePriceCents) : undefined,
      discountPercentage: isSet(object.discountPercentage) ? globalThis.Number(object.discountPercentage) : undefined,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
    };
  },

  toJSON(message: NewlyAddedProductListItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.image !== "") {
      obj.image = message.image;
    }
    if (message.priceCents !== 0) {
      obj.priceCents = Math.round(message.priceCents);
    }
    if (message.salePriceCents !== undefined) {
      obj.salePriceCents = Math.round(message.salePriceCents);
    }
    if (message.discountPercentage !== undefined) {
      obj.discountPercentage = Math.round(message.discountPercentage);
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NewlyAddedProductListItem>, I>>(base?: I): NewlyAddedProductListItem {
    return NewlyAddedProductListItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NewlyAddedProductListItem>, I>>(object: I): NewlyAddedProductListItem {
    const message = createBaseNewlyAddedProductListItem();
    message.id = object.id ?? "";
    message.title = object.title ?? "";
    message.image = object.image ?? "";
    message.priceCents = object.priceCents ?? 0;
    message.salePriceCents = object.salePriceCents ?? undefined;
    message.discountPercentage = object.discountPercentage ?? undefined;
    message.createdAt = object.createdAt ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
