// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: orders/v1/order_create.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error.js";
import { Any, SuccessResponseData } from "../../shared/v1/types.js";

export const protobufPackage = "orders.v1";

/** CreateOrder: synchronous payment capture */
export interface OrderCreateRequest {
  /** idempotency key provided by client to avoid duplicate orders */
  idempotencyKey: string;
  /** currency code (ISO 4217) */
  currencyCode: string;
  /** order-level metadata (free-form, e.g., channel, campaign utm) */
  metadata: { [key: string]: string };
  /**
   * shipping and billing addresses: use shared.v1.Any
   * provide existing address type (keeps proto flexible)
   */
  shippingAddress?: Any | undefined;
  billingAddress?:
    | Any
    | undefined;
  /** list of items to order */
  items: OrderLineItemRequest[];
  /** shipping method id or chosen shipping service */
  shippingMethod: string;
  /** coupon / promotion codes */
  promotionCodes: string[];
  /**
   * payment information token (card token, stripe payment method id, etc.)
   * For PCI, clients should use tokenization and not send raw card numbers.
   */
  paymentMethodToken: string;
  /** optional client-provided note */
  customerNote: string;
}

export interface OrderCreateRequest_MetadataEntry {
  key: string;
  value: string;
}

/** Line item in create request. Qty + source product reference. */
export interface OrderLineItemRequest {
  productId: string;
  /** optional SKU/variant id */
  variantId: string;
  sku: string;
  quantity: number;
  /**
   * Optionally client can pass a desired price verification to aid checks:
   * e.g., unit_price_cents_client = 1000 (means client expected price = 10.00)
   * This helps detect mismatches (promotions or stale inventory).
   */
  unitPriceCentsClient?:
    | string
    | undefined;
  /** metadata for line (gift wrap, special options) */
  metadata: { [key: string]: string };
}

export interface OrderLineItemRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface OrderCreateResponse {
  data?: SuccessResponseData | undefined;
  error?: AppError | undefined;
}

function createBaseOrderCreateRequest(): OrderCreateRequest {
  return {
    idempotencyKey: "",
    currencyCode: "",
    metadata: {},
    shippingAddress: undefined,
    billingAddress: undefined,
    items: [],
    shippingMethod: "",
    promotionCodes: [],
    paymentMethodToken: "",
    customerNote: "",
  };
}

export const OrderCreateRequest: MessageFns<OrderCreateRequest> = {
  encode(message: OrderCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.currencyCode !== "") {
      writer.uint32(26).string(message.currencyCode);
    }
    Object.entries(message.metadata).forEach(([key, value]) => {
      OrderCreateRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.shippingAddress !== undefined) {
      Any.encode(message.shippingAddress, writer.uint32(42).fork()).join();
    }
    if (message.billingAddress !== undefined) {
      Any.encode(message.billingAddress, writer.uint32(50).fork()).join();
    }
    for (const v of message.items) {
      OrderLineItemRequest.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.shippingMethod !== "") {
      writer.uint32(66).string(message.shippingMethod);
    }
    for (const v of message.promotionCodes) {
      writer.uint32(74).string(v!);
    }
    if (message.paymentMethodToken !== "") {
      writer.uint32(82).string(message.paymentMethodToken);
    }
    if (message.customerNote !== "") {
      writer.uint32(90).string(message.customerNote);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currencyCode = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = OrderCreateRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.metadata[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.shippingAddress = Any.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.billingAddress = Any.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.items.push(OrderLineItemRequest.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.shippingMethod = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.promotionCodes.push(reader.string());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.paymentMethodToken = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.customerNote = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderCreateRequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      currencyCode: isSet(object.currencyCode) ? globalThis.String(object.currencyCode) : "",
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      shippingAddress: isSet(object.shippingAddress) ? Any.fromJSON(object.shippingAddress) : undefined,
      billingAddress: isSet(object.billingAddress) ? Any.fromJSON(object.billingAddress) : undefined,
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => OrderLineItemRequest.fromJSON(e))
        : [],
      shippingMethod: isSet(object.shippingMethod) ? globalThis.String(object.shippingMethod) : "",
      promotionCodes: globalThis.Array.isArray(object?.promotionCodes)
        ? object.promotionCodes.map((e: any) => globalThis.String(e))
        : [],
      paymentMethodToken: isSet(object.paymentMethodToken) ? globalThis.String(object.paymentMethodToken) : "",
      customerNote: isSet(object.customerNote) ? globalThis.String(object.customerNote) : "",
    };
  },

  toJSON(message: OrderCreateRequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.currencyCode !== "") {
      obj.currencyCode = message.currencyCode;
    }
    if (message.metadata) {
      const entries = Object.entries(message.metadata);
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    if (message.shippingAddress !== undefined) {
      obj.shippingAddress = Any.toJSON(message.shippingAddress);
    }
    if (message.billingAddress !== undefined) {
      obj.billingAddress = Any.toJSON(message.billingAddress);
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => OrderLineItemRequest.toJSON(e));
    }
    if (message.shippingMethod !== "") {
      obj.shippingMethod = message.shippingMethod;
    }
    if (message.promotionCodes?.length) {
      obj.promotionCodes = message.promotionCodes;
    }
    if (message.paymentMethodToken !== "") {
      obj.paymentMethodToken = message.paymentMethodToken;
    }
    if (message.customerNote !== "") {
      obj.customerNote = message.customerNote;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderCreateRequest>, I>>(base?: I): OrderCreateRequest {
    return OrderCreateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderCreateRequest>, I>>(object: I): OrderCreateRequest {
    const message = createBaseOrderCreateRequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.currencyCode = object.currencyCode ?? "";
    message.metadata = Object.entries(object.metadata ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.shippingAddress = (object.shippingAddress !== undefined && object.shippingAddress !== null)
      ? Any.fromPartial(object.shippingAddress)
      : undefined;
    message.billingAddress = (object.billingAddress !== undefined && object.billingAddress !== null)
      ? Any.fromPartial(object.billingAddress)
      : undefined;
    message.items = object.items?.map((e) => OrderLineItemRequest.fromPartial(e)) || [];
    message.shippingMethod = object.shippingMethod ?? "";
    message.promotionCodes = object.promotionCodes?.map((e) => e) || [];
    message.paymentMethodToken = object.paymentMethodToken ?? "";
    message.customerNote = object.customerNote ?? "";
    return message;
  },
};

function createBaseOrderCreateRequest_MetadataEntry(): OrderCreateRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const OrderCreateRequest_MetadataEntry: MessageFns<OrderCreateRequest_MetadataEntry> = {
  encode(message: OrderCreateRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderCreateRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderCreateRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderCreateRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: OrderCreateRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderCreateRequest_MetadataEntry>, I>>(
    base?: I,
  ): OrderCreateRequest_MetadataEntry {
    return OrderCreateRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderCreateRequest_MetadataEntry>, I>>(
    object: I,
  ): OrderCreateRequest_MetadataEntry {
    const message = createBaseOrderCreateRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseOrderLineItemRequest(): OrderLineItemRequest {
  return { productId: "", variantId: "", sku: "", quantity: 0, unitPriceCentsClient: undefined, metadata: {} };
}

export const OrderLineItemRequest: MessageFns<OrderLineItemRequest> = {
  encode(message: OrderLineItemRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    if (message.variantId !== "") {
      writer.uint32(18).string(message.variantId);
    }
    if (message.sku !== "") {
      writer.uint32(26).string(message.sku);
    }
    if (message.quantity !== 0) {
      writer.uint32(32).uint32(message.quantity);
    }
    if (message.unitPriceCentsClient !== undefined) {
      writer.uint32(40).int64(message.unitPriceCentsClient);
    }
    Object.entries(message.metadata).forEach(([key, value]) => {
      OrderLineItemRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderLineItemRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderLineItemRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.variantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sku = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.quantity = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.unitPriceCentsClient = reader.int64().toString();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = OrderLineItemRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.metadata[entry6.key] = entry6.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderLineItemRequest {
    return {
      productId: isSet(object.productId) ? globalThis.String(object.productId) : "",
      variantId: isSet(object.variantId) ? globalThis.String(object.variantId) : "",
      sku: isSet(object.sku) ? globalThis.String(object.sku) : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      unitPriceCentsClient: isSet(object.unitPriceCentsClient)
        ? globalThis.String(object.unitPriceCentsClient)
        : undefined,
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: OrderLineItemRequest): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.variantId !== "") {
      obj.variantId = message.variantId;
    }
    if (message.sku !== "") {
      obj.sku = message.sku;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    if (message.unitPriceCentsClient !== undefined) {
      obj.unitPriceCentsClient = message.unitPriceCentsClient;
    }
    if (message.metadata) {
      const entries = Object.entries(message.metadata);
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderLineItemRequest>, I>>(base?: I): OrderLineItemRequest {
    return OrderLineItemRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderLineItemRequest>, I>>(object: I): OrderLineItemRequest {
    const message = createBaseOrderLineItemRequest();
    message.productId = object.productId ?? "";
    message.variantId = object.variantId ?? "";
    message.sku = object.sku ?? "";
    message.quantity = object.quantity ?? 0;
    message.unitPriceCentsClient = object.unitPriceCentsClient ?? undefined;
    message.metadata = Object.entries(object.metadata ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseOrderLineItemRequest_MetadataEntry(): OrderLineItemRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const OrderLineItemRequest_MetadataEntry: MessageFns<OrderLineItemRequest_MetadataEntry> = {
  encode(message: OrderLineItemRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderLineItemRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderLineItemRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderLineItemRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: OrderLineItemRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderLineItemRequest_MetadataEntry>, I>>(
    base?: I,
  ): OrderLineItemRequest_MetadataEntry {
    return OrderLineItemRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderLineItemRequest_MetadataEntry>, I>>(
    object: I,
  ): OrderLineItemRequest_MetadataEntry {
    const message = createBaseOrderLineItemRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseOrderCreateResponse(): OrderCreateResponse {
  return { data: undefined, error: undefined };
}

export const OrderCreateResponse: MessageFns<OrderCreateResponse> = {
  encode(message: OrderCreateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      SuccessResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderCreateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = SuccessResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderCreateResponse {
    return {
      data: isSet(object.data) ? SuccessResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: OrderCreateResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = SuccessResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderCreateResponse>, I>>(base?: I): OrderCreateResponse {
    return OrderCreateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderCreateResponse>, I>>(object: I): OrderCreateResponse {
    const message = createBaseOrderCreateResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? SuccessResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
