// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: orders/v1/order_line_items.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "../../shared/v1/struct.js";

export const protobufPackage = "orders.v1";

/** Order status */
export enum OrderLineItemStatus {
  ORDER_LINE_ITEM_STATUS_CREATED = 0,
  ORDER_LINE_ITEM_STATUS_CONFIRMED = 1,
  ORDER_LINE_ITEM_STATUS_SHIPPED = 2,
  ORDER_LINE_ITEM_STATUS_DELIVERED = 3,
  ORDER_LINE_ITEM_STATUS_CANCELLED = 4,
  ORDER_LINE_ITEM_STATUS_REFUNDED = 5,
  ORDER_LINE_ITEM_STATUS_REFUND_REQUESTED = 6,
  UNRECOGNIZED = -1,
}

export function orderLineItemStatusFromJSON(object: any): OrderLineItemStatus {
  switch (object) {
    case 0:
    case "ORDER_LINE_ITEM_STATUS_CREATED":
      return OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_CREATED;
    case 1:
    case "ORDER_LINE_ITEM_STATUS_CONFIRMED":
      return OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_CONFIRMED;
    case 2:
    case "ORDER_LINE_ITEM_STATUS_SHIPPED":
      return OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_SHIPPED;
    case 3:
    case "ORDER_LINE_ITEM_STATUS_DELIVERED":
      return OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_DELIVERED;
    case 4:
    case "ORDER_LINE_ITEM_STATUS_CANCELLED":
      return OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_CANCELLED;
    case 5:
    case "ORDER_LINE_ITEM_STATUS_REFUNDED":
      return OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_REFUNDED;
    case 6:
    case "ORDER_LINE_ITEM_STATUS_REFUND_REQUESTED":
      return OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_REFUND_REQUESTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderLineItemStatus.UNRECOGNIZED;
  }
}

export function orderLineItemStatusToJSON(object: OrderLineItemStatus): string {
  switch (object) {
    case OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_CREATED:
      return "ORDER_LINE_ITEM_STATUS_CREATED";
    case OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_CONFIRMED:
      return "ORDER_LINE_ITEM_STATUS_CONFIRMED";
    case OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_SHIPPED:
      return "ORDER_LINE_ITEM_STATUS_SHIPPED";
    case OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_DELIVERED:
      return "ORDER_LINE_ITEM_STATUS_DELIVERED";
    case OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_CANCELLED:
      return "ORDER_LINE_ITEM_STATUS_CANCELLED";
    case OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_REFUNDED:
      return "ORDER_LINE_ITEM_STATUS_REFUNDED";
    case OrderLineItemStatus.ORDER_LINE_ITEM_STATUS_REFUND_REQUESTED:
      return "ORDER_LINE_ITEM_STATUS_REFUND_REQUESTED";
    case OrderLineItemStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface OrderLineItem {
  id: string;
  orderId: string;
  productId: string;
  variantId: string;
  sku: string;
  /** product title snapshot */
  title: string;
  /** snapshot attributes map */
  attributes: { [key: string]: string };
  /** CHECK (quantity > 0) */
  quantity: number;
  /** Price fields in cents */
  unitPriceCents: string;
  /** optional */
  listPriceCents?:
    | string
    | undefined;
  /** optional */
  salePriceCents?:
    | string
    | undefined;
  /** total discount applied to this line (all units) */
  discountCents?:
    | string
    | undefined;
  /** tax for this line (total) */
  taxCents: string;
  /** (quantity * unit_price) - discount + tax */
  totalCents: string;
  /** array of applied offer/promotion ids */
  appliedOfferIds: string[];
  /** full product snapshot for audit/debug */
  productSnapshot?: Struct | undefined;
  status: string;
  /** Timestamps */
  createdAt: string;
  /** optional UNIX timestamp */
  updatedAt?: string | undefined;
}

export interface OrderLineItem_AttributesEntry {
  key: string;
  value: string;
}

function createBaseOrderLineItem(): OrderLineItem {
  return {
    id: "",
    orderId: "",
    productId: "",
    variantId: "",
    sku: "",
    title: "",
    attributes: {},
    quantity: 0,
    unitPriceCents: "0",
    listPriceCents: undefined,
    salePriceCents: undefined,
    discountCents: undefined,
    taxCents: "0",
    totalCents: "0",
    appliedOfferIds: [],
    productSnapshot: undefined,
    status: "",
    createdAt: "0",
    updatedAt: undefined,
  };
}

export const OrderLineItem: MessageFns<OrderLineItem> = {
  encode(message: OrderLineItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.productId !== "") {
      writer.uint32(26).string(message.productId);
    }
    if (message.variantId !== "") {
      writer.uint32(34).string(message.variantId);
    }
    if (message.sku !== "") {
      writer.uint32(42).string(message.sku);
    }
    if (message.title !== "") {
      writer.uint32(50).string(message.title);
    }
    Object.entries(message.attributes).forEach(([key, value]) => {
      OrderLineItem_AttributesEntry.encode({ key: key as any, value }, writer.uint32(58).fork()).join();
    });
    if (message.quantity !== 0) {
      writer.uint32(64).int32(message.quantity);
    }
    if (message.unitPriceCents !== "0") {
      writer.uint32(72).uint64(message.unitPriceCents);
    }
    if (message.listPriceCents !== undefined) {
      writer.uint32(80).uint64(message.listPriceCents);
    }
    if (message.salePriceCents !== undefined) {
      writer.uint32(88).uint64(message.salePriceCents);
    }
    if (message.discountCents !== undefined) {
      writer.uint32(96).uint64(message.discountCents);
    }
    if (message.taxCents !== "0") {
      writer.uint32(104).uint64(message.taxCents);
    }
    if (message.totalCents !== "0") {
      writer.uint32(112).uint64(message.totalCents);
    }
    for (const v of message.appliedOfferIds) {
      writer.uint32(122).string(v!);
    }
    if (message.productSnapshot !== undefined) {
      Struct.encode(message.productSnapshot, writer.uint32(130).fork()).join();
    }
    if (message.status !== "") {
      writer.uint32(138).string(message.status);
    }
    if (message.createdAt !== "0") {
      writer.uint32(144).uint64(message.createdAt);
    }
    if (message.updatedAt !== undefined) {
      writer.uint32(152).uint64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderLineItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderLineItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.productId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.variantId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sku = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          const entry7 = OrderLineItem_AttributesEntry.decode(reader, reader.uint32());
          if (entry7.value !== undefined) {
            message.attributes[entry7.key] = entry7.value;
          }
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.quantity = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.unitPriceCents = reader.uint64().toString();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.listPriceCents = reader.uint64().toString();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.salePriceCents = reader.uint64().toString();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.discountCents = reader.uint64().toString();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.taxCents = reader.uint64().toString();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.totalCents = reader.uint64().toString();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.appliedOfferIds.push(reader.string());
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.productSnapshot = Struct.decode(reader, reader.uint32());
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.createdAt = reader.uint64().toString();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.updatedAt = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderLineItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      productId: isSet(object.productId) ? globalThis.String(object.productId) : "",
      variantId: isSet(object.variantId) ? globalThis.String(object.variantId) : "",
      sku: isSet(object.sku) ? globalThis.String(object.sku) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      attributes: isObject(object.attributes)
        ? Object.entries(object.attributes).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      unitPriceCents: isSet(object.unitPriceCents) ? globalThis.String(object.unitPriceCents) : "0",
      listPriceCents: isSet(object.listPriceCents) ? globalThis.String(object.listPriceCents) : undefined,
      salePriceCents: isSet(object.salePriceCents) ? globalThis.String(object.salePriceCents) : undefined,
      discountCents: isSet(object.discountCents) ? globalThis.String(object.discountCents) : undefined,
      taxCents: isSet(object.taxCents) ? globalThis.String(object.taxCents) : "0",
      totalCents: isSet(object.totalCents) ? globalThis.String(object.totalCents) : "0",
      appliedOfferIds: globalThis.Array.isArray(object?.appliedOfferIds)
        ? object.appliedOfferIds.map((e: any) => globalThis.String(e))
        : [],
      productSnapshot: isSet(object.productSnapshot) ? Struct.fromJSON(object.productSnapshot) : undefined,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "0",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : undefined,
    };
  },

  toJSON(message: OrderLineItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.variantId !== "") {
      obj.variantId = message.variantId;
    }
    if (message.sku !== "") {
      obj.sku = message.sku;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.attributes) {
      const entries = Object.entries(message.attributes);
      if (entries.length > 0) {
        obj.attributes = {};
        entries.forEach(([k, v]) => {
          obj.attributes[k] = v;
        });
      }
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    if (message.unitPriceCents !== "0") {
      obj.unitPriceCents = message.unitPriceCents;
    }
    if (message.listPriceCents !== undefined) {
      obj.listPriceCents = message.listPriceCents;
    }
    if (message.salePriceCents !== undefined) {
      obj.salePriceCents = message.salePriceCents;
    }
    if (message.discountCents !== undefined) {
      obj.discountCents = message.discountCents;
    }
    if (message.taxCents !== "0") {
      obj.taxCents = message.taxCents;
    }
    if (message.totalCents !== "0") {
      obj.totalCents = message.totalCents;
    }
    if (message.appliedOfferIds?.length) {
      obj.appliedOfferIds = message.appliedOfferIds;
    }
    if (message.productSnapshot !== undefined) {
      obj.productSnapshot = Struct.toJSON(message.productSnapshot);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderLineItem>, I>>(base?: I): OrderLineItem {
    return OrderLineItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderLineItem>, I>>(object: I): OrderLineItem {
    const message = createBaseOrderLineItem();
    message.id = object.id ?? "";
    message.orderId = object.orderId ?? "";
    message.productId = object.productId ?? "";
    message.variantId = object.variantId ?? "";
    message.sku = object.sku ?? "";
    message.title = object.title ?? "";
    message.attributes = Object.entries(object.attributes ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.quantity = object.quantity ?? 0;
    message.unitPriceCents = object.unitPriceCents ?? "0";
    message.listPriceCents = object.listPriceCents ?? undefined;
    message.salePriceCents = object.salePriceCents ?? undefined;
    message.discountCents = object.discountCents ?? undefined;
    message.taxCents = object.taxCents ?? "0";
    message.totalCents = object.totalCents ?? "0";
    message.appliedOfferIds = object.appliedOfferIds?.map((e) => e) || [];
    message.productSnapshot = (object.productSnapshot !== undefined && object.productSnapshot !== null)
      ? Struct.fromPartial(object.productSnapshot)
      : undefined;
    message.status = object.status ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseOrderLineItem_AttributesEntry(): OrderLineItem_AttributesEntry {
  return { key: "", value: "" };
}

export const OrderLineItem_AttributesEntry: MessageFns<OrderLineItem_AttributesEntry> = {
  encode(message: OrderLineItem_AttributesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderLineItem_AttributesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderLineItem_AttributesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderLineItem_AttributesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: OrderLineItem_AttributesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderLineItem_AttributesEntry>, I>>(base?: I): OrderLineItem_AttributesEntry {
    return OrderLineItem_AttributesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderLineItem_AttributesEntry>, I>>(
    object: I,
  ): OrderLineItem_AttributesEntry {
    const message = createBaseOrderLineItem_AttributesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
