// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: orders/v1/orders.proto

/* eslint-disable */
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import { OrderCancelRequest, OrderCancelResponse } from "./order_cancel.js";
import { OrderCreateRequest, OrderCreateResponse } from "./order_create.js";
import { OrderGetRequest, OrderGetResponse } from "./order_get.js";
import { OrderRefundRequest, OrderRefundResponse } from "./order_refund.js";
import { OrdersListRequest, OrdersListResponse } from "./orders_list.js";
import {
  PaymentAddMethodRequest,
  PaymentAddMethodResponse,
  PaymentMakeDefaultRequest,
  PaymentMakeDefaultResponse,
  PaymentRemoveMethodRequest,
  PaymentRemoveMethodResponse,
  PaymentsListRequest,
  PaymentsListResponse,
} from "./payment_method.js";

export const protobufPackage = "orders.v1";

export interface OrdersService {
  /** Create order: synchronous payment capture. Returns order snapshot if success. */
  OrderCreate(request: DeepPartial<OrderCreateRequest>, metadata?: grpc.Metadata): Promise<OrderCreateResponse>;
  /** Get order by id */
  OrderGet(request: DeepPartial<OrderGetRequest>, metadata?: grpc.Metadata): Promise<OrderGetResponse>;
  /** List orders for user (with simple pagination) */
  OrdersList(request: DeepPartial<OrdersListRequest>, metadata?: grpc.Metadata): Promise<OrdersListResponse>;
  /** Cancel order (subject to business rules). Refunds handled separately. */
  OrderCancel(request: DeepPartial<OrderCancelRequest>, metadata?: grpc.Metadata): Promise<OrderCancelResponse>;
  /** Refund an order or order line(s) */
  OrderRefund(request: DeepPartial<OrderRefundRequest>, metadata?: grpc.Metadata): Promise<OrderRefundResponse>;
  /** Payment methods */
  PaymentAddMethod(
    request: DeepPartial<PaymentAddMethodRequest>,
    metadata?: grpc.Metadata,
  ): Promise<PaymentAddMethodResponse>;
  PaymentRemoveMethod(
    request: DeepPartial<PaymentRemoveMethodRequest>,
    metadata?: grpc.Metadata,
  ): Promise<PaymentRemoveMethodResponse>;
  PaymentMakeDefault(
    request: DeepPartial<PaymentMakeDefaultRequest>,
    metadata?: grpc.Metadata,
  ): Promise<PaymentMakeDefaultResponse>;
  PaymentsList(request: DeepPartial<PaymentsListRequest>, metadata?: grpc.Metadata): Promise<PaymentsListResponse>;
}

export class OrdersServiceClientImpl implements OrdersService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.OrderCreate = this.OrderCreate.bind(this);
    this.OrderGet = this.OrderGet.bind(this);
    this.OrdersList = this.OrdersList.bind(this);
    this.OrderCancel = this.OrderCancel.bind(this);
    this.OrderRefund = this.OrderRefund.bind(this);
    this.PaymentAddMethod = this.PaymentAddMethod.bind(this);
    this.PaymentRemoveMethod = this.PaymentRemoveMethod.bind(this);
    this.PaymentMakeDefault = this.PaymentMakeDefault.bind(this);
    this.PaymentsList = this.PaymentsList.bind(this);
  }

  OrderCreate(request: DeepPartial<OrderCreateRequest>, metadata?: grpc.Metadata): Promise<OrderCreateResponse> {
    return this.rpc.unary(OrdersServiceOrderCreateDesc, OrderCreateRequest.fromPartial(request), metadata);
  }

  OrderGet(request: DeepPartial<OrderGetRequest>, metadata?: grpc.Metadata): Promise<OrderGetResponse> {
    return this.rpc.unary(OrdersServiceOrderGetDesc, OrderGetRequest.fromPartial(request), metadata);
  }

  OrdersList(request: DeepPartial<OrdersListRequest>, metadata?: grpc.Metadata): Promise<OrdersListResponse> {
    return this.rpc.unary(OrdersServiceOrdersListDesc, OrdersListRequest.fromPartial(request), metadata);
  }

  OrderCancel(request: DeepPartial<OrderCancelRequest>, metadata?: grpc.Metadata): Promise<OrderCancelResponse> {
    return this.rpc.unary(OrdersServiceOrderCancelDesc, OrderCancelRequest.fromPartial(request), metadata);
  }

  OrderRefund(request: DeepPartial<OrderRefundRequest>, metadata?: grpc.Metadata): Promise<OrderRefundResponse> {
    return this.rpc.unary(OrdersServiceOrderRefundDesc, OrderRefundRequest.fromPartial(request), metadata);
  }

  PaymentAddMethod(
    request: DeepPartial<PaymentAddMethodRequest>,
    metadata?: grpc.Metadata,
  ): Promise<PaymentAddMethodResponse> {
    return this.rpc.unary(OrdersServicePaymentAddMethodDesc, PaymentAddMethodRequest.fromPartial(request), metadata);
  }

  PaymentRemoveMethod(
    request: DeepPartial<PaymentRemoveMethodRequest>,
    metadata?: grpc.Metadata,
  ): Promise<PaymentRemoveMethodResponse> {
    return this.rpc.unary(
      OrdersServicePaymentRemoveMethodDesc,
      PaymentRemoveMethodRequest.fromPartial(request),
      metadata,
    );
  }

  PaymentMakeDefault(
    request: DeepPartial<PaymentMakeDefaultRequest>,
    metadata?: grpc.Metadata,
  ): Promise<PaymentMakeDefaultResponse> {
    return this.rpc.unary(
      OrdersServicePaymentMakeDefaultDesc,
      PaymentMakeDefaultRequest.fromPartial(request),
      metadata,
    );
  }

  PaymentsList(request: DeepPartial<PaymentsListRequest>, metadata?: grpc.Metadata): Promise<PaymentsListResponse> {
    return this.rpc.unary(OrdersServicePaymentsListDesc, PaymentsListRequest.fromPartial(request), metadata);
  }
}

export const OrdersServiceDesc = { serviceName: "orders.v1.OrdersService" };

export const OrdersServiceOrderCreateDesc: UnaryMethodDefinitionish = {
  methodName: "OrderCreate",
  service: OrdersServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return OrderCreateRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = OrderCreateResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const OrdersServiceOrderGetDesc: UnaryMethodDefinitionish = {
  methodName: "OrderGet",
  service: OrdersServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return OrderGetRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = OrderGetResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const OrdersServiceOrdersListDesc: UnaryMethodDefinitionish = {
  methodName: "OrdersList",
  service: OrdersServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return OrdersListRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = OrdersListResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const OrdersServiceOrderCancelDesc: UnaryMethodDefinitionish = {
  methodName: "OrderCancel",
  service: OrdersServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return OrderCancelRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = OrderCancelResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const OrdersServiceOrderRefundDesc: UnaryMethodDefinitionish = {
  methodName: "OrderRefund",
  service: OrdersServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return OrderRefundRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = OrderRefundResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const OrdersServicePaymentAddMethodDesc: UnaryMethodDefinitionish = {
  methodName: "PaymentAddMethod",
  service: OrdersServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return PaymentAddMethodRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = PaymentAddMethodResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const OrdersServicePaymentRemoveMethodDesc: UnaryMethodDefinitionish = {
  methodName: "PaymentRemoveMethod",
  service: OrdersServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return PaymentRemoveMethodRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = PaymentRemoveMethodResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const OrdersServicePaymentMakeDefaultDesc: UnaryMethodDefinitionish = {
  methodName: "PaymentMakeDefault",
  service: OrdersServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return PaymentMakeDefaultRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = PaymentMakeDefaultResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const OrdersServicePaymentsListDesc: UnaryMethodDefinitionish = {
  methodName: "PaymentsList",
  service: OrdersServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return PaymentsListRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = PaymentsListResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;

    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;

      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}
