// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: users/v1/dashboard.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error";

export const protobufPackage = "users.v1";

export interface VisitsByPeriod {
  today: number;
  yesterday: number;
  lastWeek: number;
  lastMonth: number;
  lastYear: number;
}

export interface DashboardStats {
  totalProducts: number;
  totalInventoryItems: number;
  totalReviews: number;
  productVisitsCount: number;
  visitsByPeriod?: VisitsByPeriod | undefined;
  pendingOrders: number;
  totalOrders: number;
}

export interface DashboardRequest {
}

export interface DashboardResponse {
  data?: DashboardStats | undefined;
  error?: AppError | undefined;
}

function createBaseVisitsByPeriod(): VisitsByPeriod {
  return { today: 0, yesterday: 0, lastWeek: 0, lastMonth: 0, lastYear: 0 };
}

export const VisitsByPeriod: MessageFns<VisitsByPeriod> = {
  encode(message: VisitsByPeriod, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.today !== 0) {
      writer.uint32(8).int32(message.today);
    }
    if (message.yesterday !== 0) {
      writer.uint32(16).int32(message.yesterday);
    }
    if (message.lastWeek !== 0) {
      writer.uint32(24).int32(message.lastWeek);
    }
    if (message.lastMonth !== 0) {
      writer.uint32(32).int32(message.lastMonth);
    }
    if (message.lastYear !== 0) {
      writer.uint32(40).int32(message.lastYear);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VisitsByPeriod {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisitsByPeriod();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.today = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.yesterday = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lastWeek = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.lastMonth = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.lastYear = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VisitsByPeriod {
    return {
      today: isSet(object.today) ? globalThis.Number(object.today) : 0,
      yesterday: isSet(object.yesterday) ? globalThis.Number(object.yesterday) : 0,
      lastWeek: isSet(object.lastWeek) ? globalThis.Number(object.lastWeek) : 0,
      lastMonth: isSet(object.lastMonth) ? globalThis.Number(object.lastMonth) : 0,
      lastYear: isSet(object.lastYear) ? globalThis.Number(object.lastYear) : 0,
    };
  },

  toJSON(message: VisitsByPeriod): unknown {
    const obj: any = {};
    if (message.today !== 0) {
      obj.today = Math.round(message.today);
    }
    if (message.yesterday !== 0) {
      obj.yesterday = Math.round(message.yesterday);
    }
    if (message.lastWeek !== 0) {
      obj.lastWeek = Math.round(message.lastWeek);
    }
    if (message.lastMonth !== 0) {
      obj.lastMonth = Math.round(message.lastMonth);
    }
    if (message.lastYear !== 0) {
      obj.lastYear = Math.round(message.lastYear);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisitsByPeriod>, I>>(base?: I): VisitsByPeriod {
    return VisitsByPeriod.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisitsByPeriod>, I>>(object: I): VisitsByPeriod {
    const message = createBaseVisitsByPeriod();
    message.today = object.today ?? 0;
    message.yesterday = object.yesterday ?? 0;
    message.lastWeek = object.lastWeek ?? 0;
    message.lastMonth = object.lastMonth ?? 0;
    message.lastYear = object.lastYear ?? 0;
    return message;
  },
};

function createBaseDashboardStats(): DashboardStats {
  return {
    totalProducts: 0,
    totalInventoryItems: 0,
    totalReviews: 0,
    productVisitsCount: 0,
    visitsByPeriod: undefined,
    pendingOrders: 0,
    totalOrders: 0,
  };
}

export const DashboardStats: MessageFns<DashboardStats> = {
  encode(message: DashboardStats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalProducts !== 0) {
      writer.uint32(8).int32(message.totalProducts);
    }
    if (message.totalInventoryItems !== 0) {
      writer.uint32(16).int32(message.totalInventoryItems);
    }
    if (message.totalReviews !== 0) {
      writer.uint32(24).int32(message.totalReviews);
    }
    if (message.productVisitsCount !== 0) {
      writer.uint32(32).int32(message.productVisitsCount);
    }
    if (message.visitsByPeriod !== undefined) {
      VisitsByPeriod.encode(message.visitsByPeriod, writer.uint32(42).fork()).join();
    }
    if (message.pendingOrders !== 0) {
      writer.uint32(48).int32(message.pendingOrders);
    }
    if (message.totalOrders !== 0) {
      writer.uint32(56).int32(message.totalOrders);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DashboardStats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDashboardStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalProducts = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalInventoryItems = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalReviews = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.productVisitsCount = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.visitsByPeriod = VisitsByPeriod.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.pendingOrders = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalOrders = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DashboardStats {
    return {
      totalProducts: isSet(object.totalProducts) ? globalThis.Number(object.totalProducts) : 0,
      totalInventoryItems: isSet(object.totalInventoryItems) ? globalThis.Number(object.totalInventoryItems) : 0,
      totalReviews: isSet(object.totalReviews) ? globalThis.Number(object.totalReviews) : 0,
      productVisitsCount: isSet(object.productVisitsCount) ? globalThis.Number(object.productVisitsCount) : 0,
      visitsByPeriod: isSet(object.visitsByPeriod) ? VisitsByPeriod.fromJSON(object.visitsByPeriod) : undefined,
      pendingOrders: isSet(object.pendingOrders) ? globalThis.Number(object.pendingOrders) : 0,
      totalOrders: isSet(object.totalOrders) ? globalThis.Number(object.totalOrders) : 0,
    };
  },

  toJSON(message: DashboardStats): unknown {
    const obj: any = {};
    if (message.totalProducts !== 0) {
      obj.totalProducts = Math.round(message.totalProducts);
    }
    if (message.totalInventoryItems !== 0) {
      obj.totalInventoryItems = Math.round(message.totalInventoryItems);
    }
    if (message.totalReviews !== 0) {
      obj.totalReviews = Math.round(message.totalReviews);
    }
    if (message.productVisitsCount !== 0) {
      obj.productVisitsCount = Math.round(message.productVisitsCount);
    }
    if (message.visitsByPeriod !== undefined) {
      obj.visitsByPeriod = VisitsByPeriod.toJSON(message.visitsByPeriod);
    }
    if (message.pendingOrders !== 0) {
      obj.pendingOrders = Math.round(message.pendingOrders);
    }
    if (message.totalOrders !== 0) {
      obj.totalOrders = Math.round(message.totalOrders);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DashboardStats>, I>>(base?: I): DashboardStats {
    return DashboardStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DashboardStats>, I>>(object: I): DashboardStats {
    const message = createBaseDashboardStats();
    message.totalProducts = object.totalProducts ?? 0;
    message.totalInventoryItems = object.totalInventoryItems ?? 0;
    message.totalReviews = object.totalReviews ?? 0;
    message.productVisitsCount = object.productVisitsCount ?? 0;
    message.visitsByPeriod = (object.visitsByPeriod !== undefined && object.visitsByPeriod !== null)
      ? VisitsByPeriod.fromPartial(object.visitsByPeriod)
      : undefined;
    message.pendingOrders = object.pendingOrders ?? 0;
    message.totalOrders = object.totalOrders ?? 0;
    return message;
  },
};

function createBaseDashboardRequest(): DashboardRequest {
  return {};
}

export const DashboardRequest: MessageFns<DashboardRequest> = {
  encode(_: DashboardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DashboardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDashboardRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DashboardRequest {
    return {};
  },

  toJSON(_: DashboardRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DashboardRequest>, I>>(base?: I): DashboardRequest {
    return DashboardRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DashboardRequest>, I>>(_: I): DashboardRequest {
    const message = createBaseDashboardRequest();
    return message;
  },
};

function createBaseDashboardResponse(): DashboardResponse {
  return { data: undefined, error: undefined };
}

export const DashboardResponse: MessageFns<DashboardResponse> = {
  encode(message: DashboardResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      DashboardStats.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DashboardResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDashboardResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = DashboardStats.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DashboardResponse {
    return {
      data: isSet(object.data) ? DashboardStats.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: DashboardResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = DashboardStats.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DashboardResponse>, I>>(base?: I): DashboardResponse {
    return DashboardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DashboardResponse>, I>>(object: I): DashboardResponse {
    const message = createBaseDashboardResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? DashboardStats.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
