// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: users/v1/auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error.js";
import { SuccessResponseData } from "../../shared/v1/types.js";

export const protobufPackage = "users.v1";

export interface CachedUserSession {
  /** token id */
  id: string;
  token: string;
  createdAt: string;
  expiresAt: string;
  deviceId: string;
}

export interface CachedUserData {
  /** user id */
  id: string;
  isOauth: boolean;
  roles: string;
  /** like: theme:light,mobile_notification:true */
  props: string;
}

export interface CachedUser {
  session?: CachedUserSession | undefined;
  user?: CachedUserData | undefined;
}

export interface Token {
  id: string;
  userId: string;
  token: string;
  type: string;
  used: boolean;
  createdAt: string;
  expiresAt: string;
}

export interface EmailConfirmationRequest {
  email: string;
  token: string;
  tokenId: string;
}

export interface EmailConfirmationResponse {
  data?: SuccessResponseData | undefined;
  error?: AppError | undefined;
}

export interface PasswordForgotRequest {
  email: string;
}

export interface PasswordForgotResponse {
  data?: SuccessResponseData | undefined;
  error?: AppError | undefined;
}

export interface LoginRequest {
  email: string;
  password: string;
  mfa: string;
}

export interface LoginResponse {
  data?: SuccessResponseData | undefined;
  error?: AppError | undefined;
}

function createBaseCachedUserSession(): CachedUserSession {
  return { id: "", token: "", createdAt: "0", expiresAt: "0", deviceId: "" };
}

export const CachedUserSession: MessageFns<CachedUserSession> = {
  encode(message: CachedUserSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    if (message.createdAt !== "0") {
      writer.uint32(24).int64(message.createdAt);
    }
    if (message.expiresAt !== "0") {
      writer.uint32(32).int64(message.expiresAt);
    }
    if (message.deviceId !== "") {
      writer.uint32(42).string(message.deviceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CachedUserSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCachedUserSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.expiresAt = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CachedUserSession {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "0",
      expiresAt: isSet(object.expiresAt) ? globalThis.String(object.expiresAt) : "0",
      deviceId: isSet(object.deviceId) ? globalThis.String(object.deviceId) : "",
    };
  },

  toJSON(message: CachedUserSession): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.expiresAt !== "0") {
      obj.expiresAt = message.expiresAt;
    }
    if (message.deviceId !== "") {
      obj.deviceId = message.deviceId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CachedUserSession>, I>>(base?: I): CachedUserSession {
    return CachedUserSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CachedUserSession>, I>>(object: I): CachedUserSession {
    const message = createBaseCachedUserSession();
    message.id = object.id ?? "";
    message.token = object.token ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.expiresAt = object.expiresAt ?? "0";
    message.deviceId = object.deviceId ?? "";
    return message;
  },
};

function createBaseCachedUserData(): CachedUserData {
  return { id: "", isOauth: false, roles: "", props: "" };
}

export const CachedUserData: MessageFns<CachedUserData> = {
  encode(message: CachedUserData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.isOauth !== false) {
      writer.uint32(16).bool(message.isOauth);
    }
    if (message.roles !== "") {
      writer.uint32(26).string(message.roles);
    }
    if (message.props !== "") {
      writer.uint32(34).string(message.props);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CachedUserData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCachedUserData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isOauth = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.roles = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.props = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CachedUserData {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      isOauth: isSet(object.isOauth) ? globalThis.Boolean(object.isOauth) : false,
      roles: isSet(object.roles) ? globalThis.String(object.roles) : "",
      props: isSet(object.props) ? globalThis.String(object.props) : "",
    };
  },

  toJSON(message: CachedUserData): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.isOauth !== false) {
      obj.isOauth = message.isOauth;
    }
    if (message.roles !== "") {
      obj.roles = message.roles;
    }
    if (message.props !== "") {
      obj.props = message.props;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CachedUserData>, I>>(base?: I): CachedUserData {
    return CachedUserData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CachedUserData>, I>>(object: I): CachedUserData {
    const message = createBaseCachedUserData();
    message.id = object.id ?? "";
    message.isOauth = object.isOauth ?? false;
    message.roles = object.roles ?? "";
    message.props = object.props ?? "";
    return message;
  },
};

function createBaseCachedUser(): CachedUser {
  return { session: undefined, user: undefined };
}

export const CachedUser: MessageFns<CachedUser> = {
  encode(message: CachedUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      CachedUserSession.encode(message.session, writer.uint32(10).fork()).join();
    }
    if (message.user !== undefined) {
      CachedUserData.encode(message.user, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CachedUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCachedUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = CachedUserSession.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user = CachedUserData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CachedUser {
    return {
      session: isSet(object.session) ? CachedUserSession.fromJSON(object.session) : undefined,
      user: isSet(object.user) ? CachedUserData.fromJSON(object.user) : undefined,
    };
  },

  toJSON(message: CachedUser): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = CachedUserSession.toJSON(message.session);
    }
    if (message.user !== undefined) {
      obj.user = CachedUserData.toJSON(message.user);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CachedUser>, I>>(base?: I): CachedUser {
    return CachedUser.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CachedUser>, I>>(object: I): CachedUser {
    const message = createBaseCachedUser();
    message.session = (object.session !== undefined && object.session !== null)
      ? CachedUserSession.fromPartial(object.session)
      : undefined;
    message.user = (object.user !== undefined && object.user !== null)
      ? CachedUserData.fromPartial(object.user)
      : undefined;
    return message;
  },
};

function createBaseToken(): Token {
  return { id: "", userId: "", token: "", type: "", used: false, createdAt: "0", expiresAt: "0" };
}

export const Token: MessageFns<Token> = {
  encode(message: Token, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.token !== "") {
      writer.uint32(26).string(message.token);
    }
    if (message.type !== "") {
      writer.uint32(34).string(message.type);
    }
    if (message.used !== false) {
      writer.uint32(40).bool(message.used);
    }
    if (message.createdAt !== "0") {
      writer.uint32(48).int64(message.createdAt);
    }
    if (message.expiresAt !== "0") {
      writer.uint32(56).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Token {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.used = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.expiresAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Token {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      used: isSet(object.used) ? globalThis.Boolean(object.used) : false,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "0",
      expiresAt: isSet(object.expiresAt) ? globalThis.String(object.expiresAt) : "0",
    };
  },

  toJSON(message: Token): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.used !== false) {
      obj.used = message.used;
    }
    if (message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.expiresAt !== "0") {
      obj.expiresAt = message.expiresAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Token>, I>>(base?: I): Token {
    return Token.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Token>, I>>(object: I): Token {
    const message = createBaseToken();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.token = object.token ?? "";
    message.type = object.type ?? "";
    message.used = object.used ?? false;
    message.createdAt = object.createdAt ?? "0";
    message.expiresAt = object.expiresAt ?? "0";
    return message;
  },
};

function createBaseEmailConfirmationRequest(): EmailConfirmationRequest {
  return { email: "", token: "", tokenId: "" };
}

export const EmailConfirmationRequest: MessageFns<EmailConfirmationRequest> = {
  encode(message: EmailConfirmationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    if (message.tokenId !== "") {
      writer.uint32(26).string(message.tokenId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailConfirmationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailConfirmationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tokenId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailConfirmationRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      tokenId: isSet(object.tokenId) ? globalThis.String(object.tokenId) : "",
    };
  },

  toJSON(message: EmailConfirmationRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.tokenId !== "") {
      obj.tokenId = message.tokenId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailConfirmationRequest>, I>>(base?: I): EmailConfirmationRequest {
    return EmailConfirmationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailConfirmationRequest>, I>>(object: I): EmailConfirmationRequest {
    const message = createBaseEmailConfirmationRequest();
    message.email = object.email ?? "";
    message.token = object.token ?? "";
    message.tokenId = object.tokenId ?? "";
    return message;
  },
};

function createBaseEmailConfirmationResponse(): EmailConfirmationResponse {
  return { data: undefined, error: undefined };
}

export const EmailConfirmationResponse: MessageFns<EmailConfirmationResponse> = {
  encode(message: EmailConfirmationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      SuccessResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailConfirmationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailConfirmationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = SuccessResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailConfirmationResponse {
    return {
      data: isSet(object.data) ? SuccessResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: EmailConfirmationResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = SuccessResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailConfirmationResponse>, I>>(base?: I): EmailConfirmationResponse {
    return EmailConfirmationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailConfirmationResponse>, I>>(object: I): EmailConfirmationResponse {
    const message = createBaseEmailConfirmationResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? SuccessResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBasePasswordForgotRequest(): PasswordForgotRequest {
  return { email: "" };
}

export const PasswordForgotRequest: MessageFns<PasswordForgotRequest> = {
  encode(message: PasswordForgotRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PasswordForgotRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePasswordForgotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PasswordForgotRequest {
    return { email: isSet(object.email) ? globalThis.String(object.email) : "" };
  },

  toJSON(message: PasswordForgotRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PasswordForgotRequest>, I>>(base?: I): PasswordForgotRequest {
    return PasswordForgotRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PasswordForgotRequest>, I>>(object: I): PasswordForgotRequest {
    const message = createBasePasswordForgotRequest();
    message.email = object.email ?? "";
    return message;
  },
};

function createBasePasswordForgotResponse(): PasswordForgotResponse {
  return { data: undefined, error: undefined };
}

export const PasswordForgotResponse: MessageFns<PasswordForgotResponse> = {
  encode(message: PasswordForgotResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      SuccessResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PasswordForgotResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePasswordForgotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = SuccessResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PasswordForgotResponse {
    return {
      data: isSet(object.data) ? SuccessResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: PasswordForgotResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = SuccessResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PasswordForgotResponse>, I>>(base?: I): PasswordForgotResponse {
    return PasswordForgotResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PasswordForgotResponse>, I>>(object: I): PasswordForgotResponse {
    const message = createBasePasswordForgotResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? SuccessResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseLoginRequest(): LoginRequest {
  return { email: "", password: "", mfa: "" };
}

export const LoginRequest: MessageFns<LoginRequest> = {
  encode(message: LoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.mfa !== "") {
      writer.uint32(26).string(message.mfa);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.mfa = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      mfa: isSet(object.mfa) ? globalThis.String(object.mfa) : "",
    };
  },

  toJSON(message: LoginRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.mfa !== "") {
      obj.mfa = message.mfa;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginRequest>, I>>(base?: I): LoginRequest {
    return LoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginRequest>, I>>(object: I): LoginRequest {
    const message = createBaseLoginRequest();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    message.mfa = object.mfa ?? "";
    return message;
  },
};

function createBaseLoginResponse(): LoginResponse {
  return { data: undefined, error: undefined };
}

export const LoginResponse: MessageFns<LoginResponse> = {
  encode(message: LoginResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      SuccessResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = SuccessResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginResponse {
    return {
      data: isSet(object.data) ? SuccessResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: LoginResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = SuccessResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginResponse>, I>>(base?: I): LoginResponse {
    return LoginResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginResponse>, I>>(object: I): LoginResponse {
    const message = createBaseLoginResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? SuccessResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
